### ISSUE TITLE
If cannot be minified, Javascript asset without code is served on production

### ISSUE THREAD

**Issue by mjcmatrix** [bertramdev/asset-pipeline#101]
### Scenario

Grails application.

Recently, after some code change, UglifyJs within asset-pipeline was no longer able to minify one of my javascript files (`ajax.js`).

Minification of the asset fails during the build.

The build output contains 'Errors 1, warnings 0' when minifying this one asset. The build succeeds. The application gets deployed to production.

The cause of UglifyJS failing to minify this javascript asset in this case was that I had added a default parameter to a function (EC6 feature). UglifyJS does not support this. _(Google closure compiler does.)_

### The Issue

In production, `ajax.js`, as fetched by the browser, contains no code. It only contains one line: `//# sourceMappingURL=ajax.js.map` This only happens for a production build, where assets have been processed by asset-pipeline, and does not happen in development mode.

The effect on the application is that all javascript functionality within the app silently breaks only on production. Inspection of network traffic in the browser reveals a normal-looking HTTP status 200 on the `ajax.js` fetch, as expected, but the console is empty and none of the expected javascript code runs. Only looking inside the javascript retrieved by the browser, using the inspector, reveals that the all the javascript code is missing from the asset file.

### Expected behaviour

If minify fails, either:

1. The build fails with an error, or;
2. The javascript asset is not minified (skipped) but is still served intact on production.

### Actual behaviour
- Production war build succeeds.
- A javascript file that contains no code is served on production. The javascript file contains only a source mapping comment: `//# sourceMappingURL=ajax.js.map` 
- The build output contains a message  'Errors 1, warnings 0' for one asset within many assets being processed.

### Environment
  - Latest stable Grails 3.1.8
  - Asset-pipeline 2.9.1
  - Production war build of an application

### Steps to reproduce
1. Create a new grails web app
2. Create a new `assets/javascript/test.js` javascript file containing a function that has a default parameter, or that otherwise causes an error in UglifyJs.
3. Include this javascript from the test app's web page and call the function from it.
4. In the browser's inspector, verify that the javascript is valid in the development environment
5. Do a production war build and deploy it to a container such as Tomcat.
6. Observe that the javascript asset fails to compile (minify) but that the build succeeds.
7. Open the browser's inspector and activate the network tab to capture requests.
8. Visit the test page on production
9. In the browser's inspector, find `test.js` and look at the Response. The code should be missing.

**Comment by davydotcom** [comment]
skipping minifcation in next build if it fails

**Comment by mgross-letsdev** [comment]
Using Grails 3.2.6 I had the same problem. In my case the problem was caused because of the usage of
`const MY_SELECTOR_CONST = "#myConstDivId"`

There was no error when building the war, but the minified JS was empty.

Now I replaced the constants in JS with
`var MY_SELECTOR_CONST = "#myConstDivId"`

If someone has problems with minifyJs, it can be turned of in build.gradle
`assets {
    minifyJs = false
    minifyCss = true
}`

**Comment by ppazos** [comment]
I can confirm the minifier js doesn't work with 'const', maybe with lambda functions neither. I guess this will be a problem for anyone using ES6.

**Comment by davydotcom** [comment]
There is a much newer version of asset pipeline that supports ES6 concepts for mini faction . Please update to latest and try again.
