### ISSUE TITLE
Grails 3.1.8 it doesn't work assetPath

### ISSUE THREAD

**Issue by janpenspain** [bertramdev/asset-pipeline#103]
Hi,
my set up is tomcat 8 java 8 grails 3.1.8  

compile "org.grails.plugins:asset-pipeline:3.0.15"

I have this code line,
`<td align="left" valign="middle"><img src="${assetPath(src: 'logo-mail.png', absolute: true)}" width="230" height="90" style="display: block; width: 230px; height: 90px;" border="0" class="img-max"></td>
`
if deploy from intelliJ this app works well, but I generate a war and deploy from tomcat then the app doesn't work.

Error executing tag : You cannot read the scheme in non-request rendering operations, class:class org.grails.taglib.GrailsTagException, stackTraceDepth:177, 
cause:java.lang.UnsupportedOperationException: You cannot read the scheme in non-request rendering operations, lineNumber:16,

The same app from grails 2.5 doesn't show anything error.

**Comment by davydotcom** [comment]
Is this an email template?

**Comment by janpenspain** [comment]
Yes is a template for body of plugin mail

**Comment by janpenspain** [comment]
I  don't understand because the 'assetpath' works in  grails 2.5 but doesn't work in 3.1.8, may be the combinación of versión of plugin mail and asset-pipeline??

**Comment by davydotcom** [comment]
are you setting the serverURL for production?

**Comment by janpenspain** [comment]
Thanks you , when I set serverUtrl, it Works, you are a  very good professional
