### ISSUE TITLE
Set `setIsIndentedSyntaxSrc` option to`true` for sass file in jsass

### ISSUE THREAD

**Issue by XingjianXu** [bertramdev/asset-pipeline#105]
Currently (version 2.9.4), asset pipeline can not compile sass file correctly, they must use scss code style.

For example, in application.sass:
```
.div1
  div2
    color: red
```
will not compile, jsass yielding a CompilationException.

When the application.sass changes to the scss coding style:
```
.div1 {
  .div2 {
    color: red
  }
}
```
Ok, no problem.

API http://jsass.readthedocs.io/en/latest/options.html#sass-syntax may fix this issue.

**Comment by davydotcom** [comment]
change made for next release 2.9.6
