### ISSUE TITLE
Two different asset pipeline plugins for grails 3?

### ISSUE THREAD

**Issue by snimavat** [bertramdev/asset-pipeline#107]
Can some one clarify why there are two different asset pipline plugins

1 https://bintray.com/bertramlabs/asset-pipeline/asset-pipeline-grails
2 https://bintray.com/grails/plugins/asset-pipeline

Which is official, or being developed by original developer ?

**Comment by ZacharyKlein** [comment]
@snimavat The readme file answers that question I think:

> NOTE: This repository is only for supporting the Grails 2 module of asset-pipeline. For grails3 see the main repository at asset-pipeline.
via https://github.com/bertramdev/grails-asset-pipeline

**Comment by davydotcom** [comment]
1 is official, 2 was created for the original grails 3 release but was version mismatched with the rest of the pipeline plugins so it was brought back inline

**Comment by snimavat** [comment]
@davydotcom this is still confusing..

The docs on https://bintray.com/bertramlabs/asset-pipeline/asset-pipeline-grails says 

The plugin should be installed like this

```

buildscript {
    dependencies {        
        classpath 'com.bertramlabs.plugins:asset-pipeline-gradle:2.8.0'
    }
}
apply plugin: 'asset-pipeline'

dependencies {        
    runtime 'org.grails.plugins:asset-pipeline:3.2.0'
}

```

if "asset-pipeline" is just for grails 2, and grails 3 should use "grails-asset-pipeline"
Why the readme on github says to use runtime 'org.grails.plugins:asset-pipeline:3.2.0' -- is the readme outdated ?

**Comment by davydotcom** [comment]
Yes the official manual is now at www.asset-pipeline.com

I'll fix this readme good eye

**Comment by snimavat** [comment]
@davydotcom docs fix, if you want to merge - https://github.com/bertramdev/asset-pipeline/pull/112
