### ISSUE TITLE
Plug-in execution log?

### ISSUE THREAD

**Issue by aadrian** [bertramdev/asset-pipeline#115]
Hi,

Is there a plug-in execution log? To see what files were processed and how and why?
I can only see the results in the ```/target/``` directory, and that's already too late.

Even if I call the ```asset-precompile --verbose" won't help with what the plug-in itself is doing.

Thank you.

**Comment by davydotcom** [comment]
The build log should contain it as it shows up in the build events

**Comment by gregorydickson** [comment]
In Grails 3, I set my logback.groovy to have these:
root(ERROR, ['STDOUT'])
logger("asset.pipeline.jsass", DEBUG, ['STDOUT'], false)
logger("asset.pipeline", DEBUG, ['STDOUT'], false)

in order to see logging from the asset pipeline, and the sass part specficially.

**Comment by gregorydickson** [comment]
I have an example app that shows usage:
https://github.com/gregorydickson/grails-3-sass-asset-pipeline-example

**Comment by aadrian** [comment]
@gregorydickson thank you for the examples.
