### ISSUE TITLE
Changes to dependent SASS files included via @import not auto-detected

### ISSUE THREAD

**Issue by amcclain** [bertramdev/asset-pipeline#120]
We updated from the 1.x plugin to the latest 2.11 versions - using both the core asset plugin and the SASS plugin for Grails 2.x development.  

The performance improvements are wonderful, but the latest versions do not automatically respond to updates made to dependent/child SASS files when those files are included in a watched parent file via `@import` instead of the requires directives. (This was a feature of the prior Compass-based implementations - not sure if that was due to the use of Compass or provided by the plugin code itself.)

The `@import` includes are a key part of SASS when you want the child fragments to have access to variables and mix-ins defined or imported by the parent, so it's not always convenient or sensible to only use the requires directives, which have a very different behavior.

Could the SassAssetFile directivePattern be modified to also pick up import statements? Or would that have other, undesired effects, or is there some other mechanism that could be used?  Thanks!

**Comment by TomTirapani** [comment]
+1

**Comment by davydotcom** [comment]
This sounds like a bug as it is a feature provided by asset pipeline
itself... I'll get it fixed and have a build out this week.

**Comment by amcclain** [comment]
Great - thanks so much! Let us know if we can help to test anything out - very happy to do so.

**Comment by gregorydickson** [comment]
+1

**Comment by davydotcom** [comment]
Should be fixed in 2.11.2

**Comment by amcclain** [comment]
Looking good now - thanks again!  🚀
