### ISSUE TITLE
Accept js resources with names containing '$'

### ISSUE THREAD

**Issue by trygvea** [bertramdev/asset-pipeline#125]
We use core.js version 1.2.7, which have lots of file names starting with a dollar-sign, ie. core-js@1.2.7/library/modules/$.core.js etc.
These resources do not load in the browser (404), because the paths are not correctly rewritten (through the _asset_pipeline_require pattern).

A probable resolution is to add '\$' to the URL_CALL_PATTERN regexp in file JsRequireProcessor.groovy, to make the url path rewriting work.
(Add the dollar inside the square brackets, so that the new regexp is: 
  URL_CALL_PATTERN = ~/require((?:\s_)(['"]?)([a-zA-Z0-9-_.:\/@#? &+%=\$]++)\1?(?:\s_))/
)

Similar regexps are also used in files JsProcessor, CssProcessor, and partly also in HtmlProcessor, these should probably be aligned.

**Comment by rlovtangen** [comment]
The problem arise when loading http://localhost:8080/assets/jspm_packages/npm/core-js@1.2.7/library/fn/promise.js
which has the following content:
````
/* */
require('../modules/es6.object.to-string');
require('../modules/es6.string.iterator');
require('../modules/web.dom.iterable');
require('../modules/es6.promise');
module.exports = require('../modules/$.core').Promise;
````
In Grails 2.5.0 with asset-pipeline 2.9.1, this file is rendered as is. But in Grails 3.1.11 with asset-pipeline 2.11.2 it results in:

````

var _asset_pipeline_require = function(path) {
	var module = _asset_pipeline_modules[path];
	if(module != undefined) {
		return module().exports;
	}
	return null;
};

var _asset_pipeline_modules = _asset_pipeline_modules || {};
_asset_pipeline_modules['jspm_packages/npm/core-js@1.2.7/library/modules/es6.object.to-string.js'] = 
(function() {
  var module = {exports: {}};
  var exports = module.exports;

  /* */ 
"format cjs";


  return module;
})
;
_asset_pipeline_modules['jspm_packages/npm/core-js@1.2.7/library/modules/es6.string.iterator.js'] = 
(function() {
  var module = {exports: {}};
  var exports = module.exports;

  /* */ 
'use strict';
var $at = require('./$.string-at')(true);
require('./$.iter-define')(String, 'String', function(iterated) {
  this._t = String(iterated);
  this._i = 0;
}, function() {
  var O = this._t,
      index = this._i,
      point;
  if (index >= O.length)
    return {
      value: undefined,
      done: true
    };
  point = $at(O, index);
  this._i += point.length;
  return {
    value: point,
    done: false
  };
});


  return module;
})
;

...


_asset_pipeline_require('jspm_packages/npm/core-js@1.2.7/library/modules/es6.object.to-string.js');
_asset_pipeline_require('jspm_packages/npm/core-js@1.2.7/library/modules/es6.string.iterator.js');
_asset_pipeline_require('jspm_packages/npm/core-js@1.2.7/library/modules/web.dom.iterable.js');
_asset_pipeline_require('jspm_packages/npm/core-js@1.2.7/library/modules/es6.promise.js');
module.exports = require('../modules/$.core').Promise;
````

i.e. the content of each file that is required is inlined and require is replaced with _asset_pipeline_require.

When `library/modules/es6.string.iterator.js` does a `require('./$.string-at')` it should probably load `library/modules/$.string-at.js` (relative to es6.string.iterator.js), but it looks like it tries to load `library/fn/$.string-at.js` (relative to promise.js) which results in 404.

**Comment by rlovtangen** [comment]
This change in behaviour was introduced by asset-pipeline 2.10.0.
2.9.3 doesn't have this issue.
I'm about to create a demo application.

**Comment by davydotcom** [comment]
Adding $ to pattern matcher

**Comment by rlovtangen** [comment]
Great!
Uploaded an example project at https://github.com/rlovtangen/bugreport125-asset-pipeline

**Comment by rlovtangen** [comment]
Has this fix been applied yet? Still an issue in 2.12.0.

**Comment by davydotcom** [comment]
fixed in 2.12.1

**Comment by rlovtangen** [comment]
Thanks for the fast response :)

With 2.12.1, http://localhost:8080/assets/jspm_packages/npm/core-js@1.2.7/library/fn/promise.js is still being rewritten, but with some modifications compared to 2.12.0. I guess that is as expected?
What's changed from 2.12.0 to 2.12.1 is for example:
```
  /* */
'use strict';
var $at = require('./$.string-at')(true);
require('./$.iter-define')(String, 'String', function(iterated) {
  this._t = String(iterated);
  this._i = 0;
}, function() {
  var O = this._t,
      index = this._i,
      point;
  if (index >= O.length)
    return {
      value: undefined,
      done: true
    };
  point = $at(O, index);
  this._i += point.length;
  return {
    value: point,
    done: false
  };
});


  return module;
})
;
```

to

```
  /* */
'use strict';
var $at = _asset_pipeline_require('jspm_packages/npm/core-js@1.2.7/library/modules/$.string-at.js')(true);
_asset_pipeline_require('jspm_packages/npm/core-js@1.2.7/library/modules/$.iter-define.js')(String, 'String', function(iterated) {
  this._t = String(iterated);
  this._i = 0;
}, function() {
  var O = this._t,
      index = this._i,
      point;
  if (index >= O.length)
    return {
      value: undefined,
      done: true
    };
  point = $at(O, index);
  this._i += point.length;
  return {
    value: point,
    done: false
  };
});


  return module;
})
;
```

and then right beneath, the content of `$.string-at.js` is inlined rather than loading http://localhost:8080/assets/jspm_packages/npm/core-js@1.2.7/modules/$.string-at.js separately:

```
_asset_pipeline_modules['jspm_packages/npm/core-js@1.2.7/library/modules/$.string-at.js'] =
(function() {
  var module = {exports: {}};
  var exports = module.exports;

  /* */
var toInteger = _asset_pipeline_require('jspm_packages/npm/core-js@1.2.7/library/modules/$.to-integer.js'),
    defined = _asset_pipeline_require('jspm_packages/npm/core-js@1.2.7/library/modules/$.defined.js');
module.exports = function(TO_STRING) {
  return function(that, pos) {
    var s = String(defined(that)),
        i = toInteger(pos),
        l = s.length,
        a,
        b;
    if (i < 0 || i >= l)
      return TO_STRING ? '' : undefined;
    a = s.charCodeAt(i);
    return a < 0xd800 || a > 0xdbff || i + 1 === l || (b = s.charCodeAt(i + 1)) < 0xdc00 || b > 0xdfff ? TO_STRING ? s.charAt(i) : a : TO_STRING ? s.slice(i, i + 2) : (a - 0xd800 << 10) + (b - 0xdc00) + 0x10000;
  };
};


  return module;
})
;
```

and then `$.string-at.js`' dependencies `$.to-integer.js` and `$.defined.js` is inlined as well.

Now I no longer get errors where files couldn't be loaded because of wrong path.
But we do get lots of errors from React of type:

```
invariant.js:17 Uncaught Error: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).(…)
```

I haven't dived deep into what this could be, but as the error message says, it can be two things. I don't expect it to be invalide refs, as we then probably would have seen the same error when using asset-pipeline 2.9.3. So it's probably multiple copies of react. Any idea how that could happen?

**Comment by rlovtangen** [comment]
Should I create a separate issue for this? We don't get this error with 2.9.3. Also, we don't get the error in 2.12.1 when js is bundled for production, only when we have these js files that are now being rewritten by asset-pipeline.

**Comment by rlovtangen** [comment]
![image](https://cloud.githubusercontent.com/assets/233839/20929251/9c6e0e6a-bbc9-11e6-9ef8-1baa6035b66b.png)
