### ISSUE TITLE
Could not find asset-pipeline.zip

### ISSUE THREAD

**Issue by NomNuggetNom** [bertramdev/asset-pipeline#128]
I'm getting an error complaining that there is no `asset-pipeline.zip`:

```
Could not find asset-pipeline.zip (org.grails.plugins:asset-pipeline:3.2.1).
Searched in the following locations:
    https://repo.grails.org/grails/core/org/grails/plugins/asset-pipeline/3.2.1/asset-pipeline-3.2.1.zip
```
However, this error only occurs when I try hooking in an asset, like the handlebars asset:
`    assets "org.grails.plugins:handlebars-asset-pipeline:2.11.0`
(although I have tested two different asset pipeline plugins and they both give the same error)

Any idea what's up with this? Here's my full build.gradle (yes it's huge sorry):
```
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://repo.grails.org/grails/core" }
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.10.0"
        classpath "org.grails.plugins:hibernate5:6.0.0"
    }
}

plugins {
    id "com.bertramlabs.asset-pipeline" version "2.10.0"
}

version "0.1"
group "nweb"

apply plugin: "idea"
apply plugin: "war"
apply plugin: "org.grails.grails-web"
apply plugin: "org.grails.grails-gsp"

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
    maven { url "https://repo.grails.org/grails/plugins" }
}

dependencyManagement {
    imports {
        mavenBom "org.grails:grails-bom:$grailsVersion"
    }
    applyMavenExclusions false
}

dependencies {
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.grails:grails-core"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    compile "org.springframework.boot:spring-boot-starter-tomcat"
    compile "org.grails:grails-dependencies"
    compile "org.grails:grails-web-boot"
    compile "org.grails.plugins:cache"
    compile "org.grails.plugins:scaffolding"
    compile "org.grails.plugins:hibernate5"
    compile "org.hibernate:hibernate-core:5.1.1.Final"
    compile "org.hibernate:hibernate-ehcache:5.1.1.Final"
    console "org.grails:grails-console"
    profile "org.grails.profiles:web"
    provided "org.codehaus.groovy:groovy-ant"
    runtime "com.bertramlabs.plugins:asset-pipeline-grails:2.11.2"
    runtime "com.h2database:h2"
    assets "org.grails.plugins:handlebars-asset-pipeline:2.11.0"
    testCompile "org.grails:grails-plugin-testing"
    testCompile "org.grails.plugins:geb"
    testRuntime "org.seleniumhq.selenium:selenium-htmlunit-driver:2.47.1"
    testRuntime "net.sourceforge.htmlunit:htmlunit:2.18"
}


assets {
    minifyJs = true
    minifyCss = true
}
```

**Comment by davydotcom** [comment]
your applying both a gradle plugin in build classpath and plugins{} also its version does not match asset-pipeline-grails as it should.

**Comment by NomNuggetNom** [comment]
@davydotcom Which one should I keep? I'm not really familiar with this system, sorry! Also, are you saying the `handlebars-asset-pipeline` version needs to match the `asset-pipeline-grails` version? I tried changing the handlebars plugin to 2.11.2 but there is no version that matches.

**Comment by magx2** [comment]
Sorry but I have the same problem and I don't know what should I delete.

I've go this problem after adding this line in my ```build.gradle```:

    assets group: 'org.grails.plugins', name: 'coffee-asset-pipeline', version: '2.12.4'

Below I attach my configuration (was created by Grails with profile ```angular```:

    buildscript {
        repositories {
            mavenLocal()
            maven { url "https://repo.grails.org/grails/core" }
            mavenCentral()
        }
        dependencies {
            classpath "org.grails:grails-gradle-plugin:$grailsVersion"
            classpath "gradle.plugin.com.craigburke.gradle:karma-gradle:1.4.3"
            classpath "com.craigburke.gradle:client-dependencies:1.3.1"
            classpath "org.grails.plugins:angular-scaffolding:1.0.1"
            classpath "org.grails.plugins:hibernate5:6.0.4"
            classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.11.6"
            classpath "org.grails.plugins:views-gradle:1.1.2"
        }
    }

    version rootProject.version
    group rootProject.group

    apply plugin:"eclipse"
    apply plugin:"idea"
    apply plugin:"war"
    apply plugin:"org.grails.grails-web"
    apply plugin:"org.grails.grails-gsp"
    apply plugin:"com.craigburke.karma"
    apply plugin:"com.craigburke.client-dependencies"
    apply plugin:"asset-pipeline"
    apply plugin:"org.grails.plugins.views-json"

    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
        maven { url "https://repo.grails.org/grails/plugins/" }
        mavenCentral()
    }

    dependencyManagement {
        imports {
            mavenBom "org.grails:grails-bom:$grailsVersion"
        }
        applyMavenExclusions false
    }

    dependencies {
        assets "com.craigburke.angular:angular-template-asset-pipeline:2.3.0"
        assets "com.craigburke.angular:angular-annotate-asset-pipeline:2.4.0"
        assets "com.craigburke:js-closure-wrap-asset-pipeline:1.2.0"
        assets group: 'org.grails.plugins', name: 'coffee-asset-pipeline', version: '2.12.4'

        compile "org.springframework.boot:spring-boot-starter-logging"
        compile "org.springframework.boot:spring-boot-autoconfigure"
        compile "org.grails:grails-core"
        compile "org.springframework.boot:spring-boot-starter-actuator"
        compile "org.springframework.boot:spring-boot-starter-tomcat"
        compile "org.grails:grails-plugin-url-mappings"
        compile "org.grails:grails-plugin-rest"
        compile "org.grails:grails-plugin-codecs"
        compile "org.grails:grails-plugin-interceptors"
        compile "org.grails:grails-plugin-services"
        compile "org.grails:grails-plugin-datasource"
        compile "org.grails:grails-plugin-databinding"
        compile "org.grails:grails-plugin-async"
        compile "org.grails:grails-web-boot"
        compile "org.grails:grails-logging"
        compile "org.grails.plugins:cache"
        compile "org.grails:grails-plugin-gsp"
        compile "org.grails.plugins:angular-scaffolding:1.0.1"
        compile "org.grails.plugins:hibernate5"
        compile "org.hibernate:hibernate-core:5.1.2.Final"
        compile "org.hibernate:hibernate-ehcache:5.1.2.Final"
        compile "org.grails.plugins:views-json"
        compile "org.grails.plugins:views-json-templates"
        compile "org.grails.plugins:spring-security-rest:2.0.0.M2"

        console "org.grails:grails-console"

        profile "org.grails.profiles:angular"

        runtime "com.h2database:h2"
        runtime "com.bertramlabs.plugins:asset-pipeline-grails:2.11.6"
    
        testCompile "org.grails:grails-plugin-testing"
        testCompile "org.grails.plugins:geb"
        testCompile "org.grails:grails-datastore-rest-client"

        testRuntime "org.seleniumhq.selenium:selenium-htmlunit-driver:2.47.1"
        testRuntime "net.sourceforge.htmlunit:htmlunit:2.18"
    }

    bootRun {
        jvmArgs('-Dspring.output.ansi.enabled=always')
    }


    clientDependencies {
        npm {
            'angular'('1.5.x', into: 'angular') {
                include 'angular.js'
            }
            'angular-mocks'('1.5.x', into: 'angular') {
                include 'angular-mocks.js'
            }
            'angular-resource'('1.5.x', into: 'angular') {
                include 'angular-resource.js'
            }
            'angular-ui-bootstrap'('1.3.x', into: 'angular') {
                include 'ui-bootstrap-tpls.js'
            }
            'angular-route'('1.5.x', into: 'angular') {
                include 'angular-route.js'
            }
            'angular-ui-router'('0.2.x', into: 'angular', from: 'release') {
                include 'angular-ui-router.js'
            }
            'bootstrap'('3.3.x', into: 'bootstrap', from: 'dist/css') {
                include 'bootstrap.css'
            }
        }
    }

    karma {
        dependencies(['karma-wrap-preprocessor'])

        profile 'angularJS'

        preprocessors = [
            'grails-app/assets/javascripts/**/*.js': ['wrap']
        ]

        wrapPreprocessor = [
            template: "(function () { 'use strict';  <%= contents %> })()"
        ]
    }



    assets {
        minifyJs = true
        minifyCss = true
    }

**Comment by timbonicus** [comment]
In case anyone else runs into this - try commenting out novel dependencies that you have. In my case, I had a dependency declared on a Grails plugin that itself depends on asset-pipeline and was *not* upgraded to Grails 3.

**Comment by magx2** [comment]
i do not have have novel plugin

**Comment by magx2** [comment]
To work I needed to exclude ```asset-pipeline```

```groovy
assets('org.grails.plugins:coffee-asset-pipeline:2.12.4') {
    exclude group: "org.grails.plugins", module: "asset-pipeline"
}
```

**Comment by davydotcom** [comment]
Did you try latest versions by chance?

**Comment by magx2** [comment]
Of what?

**Comment by davydotcom** [comment]
all the main asset-pipeline plugins have the same version now you show,d be using the same version across them. i.e. asset-pipeline-grails and coffee-asset-pipeline should have the same version. Even coffee-asset-pipeline is the wrong group. you are referencing a grails 2 library instead of a grails3 one. 

http://www.asset-pipeline.com/plugins

Lists all the grails 3 based plugin options . Ensure asset-pipeline-gradle is also the latest 

`org.grails.plugins` is the wrong group for most asset-pipeline plugins for grails 3. Most of them are : 'com.bertramlabs.plugins'

**Comment by magx2** [comment]
You are right. This plugin works great: ```assets 'com.bertramlabs.plugins:coffee-asset-pipeline:2.12.9'```
