### ISSUE TITLE
Using Thymeleaf and Spring Boot

### ISSUE THREAD

**Issue by newtonrd** [bertramdev/asset-pipeline#133]
Just wondering if you know how to use Thymeleaf to read the digest version of the assets. It was left as a TODO in the SpringBoot projection.

**Comment by astiob** [comment]
Moreover, the manual erroneously and misleadingly [states](http://www.asset-pipeline.com/manual/#configuration) that this is already supported:

> By default both digested named versions of assets as well as non digested named versions are generated as well as the gzip equivalents. Some frameworks dont actually need the non digested named versions (`ratpack`, `grails`, `spring-boot`, and `servlets`). These frameworks take advantage of the `manifest.properties` file discussed earlier in the documentation to properly map requests for non digested file names to the digested equivalent and preserve compatibility with libraries that may not work well with digested file names.
>
> TIP | Change `skipNonDigests` to true to help reduce the file size of your final generated project.

Actually, setting `skipNonDigests` to true and referring to assets like `th:src="@{/assets/blah.css}"` only results in 404 errors when the browser attempts to access the assets in production mode. (Development mode works, but then `skipNonDigests` is not relevant to development mode at all, as far as I understand.)

Ideally, URLs in Thymeleaf templates should be automatically rewritten to include the digest in the file name in production mode. I think requests for non-digested file names should *not* be automatically mapped to the right files (when `skipNonDigests` is true), but in case someone else wants this behaviour, some sort of option could be added.

**Comment by astiob** [comment]
Here’s my solution:

```java
import asset.pipeline.*;
import java.util.*;
import javax.servlet.http.*;
import org.springframework.context.annotation.*;
import org.springframework.core.io.*;
import org.springframework.web.servlet.config.annotation.*;
import org.springframework.web.servlet.resource.*;

@Configuration
public class WebMvcConfigurer extends WebMvcConfigurerAdapter {
	private static class AssetResolver extends AbstractResourceResolver {
		@Override
		protected Resource
		resolveResourceInternal(HttpServletRequest request,
		                        String requestPath,
		                        List<? extends Resource> locations,
		                        ResourceResolverChain chain) {
			return chain.resolveResource(request, requestPath, locations);
		}

		@Override
		protected String
		resolveUrlPathInternal(String resourceUrlPath,
		                       List<? extends Resource> locations,
		                       ResourceResolverChain chain) {
			String path = resolveAssetPath(resourceUrlPath);
			if (path != null)
				return path;
			return chain.resolveUrlPath(resourceUrlPath, locations);
		}

		private static String resolveAssetPath(String path) {
			Properties manifest = AssetPipelineConfigHolder.manifest;
			if (manifest == null)
				return null;

			if (path.startsWith("/"))
				path = path.substring(1);
			return manifest.getProperty(path);
		}
	}

	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry.addResourceHandler("/assets/*")
		        .resourceChain(true)
		        .addResolver(new AssetResolver());
	}
}
```

(I hereby release this code into the public domain. Although if this ever lands in an open-source project, I’d appreciate being credited.)

Put this class somewhere that Spring Boot’s autoconfiguration will find it, and set `spring.resources.chain.enabled=true` in your `application.properties` file (or other Spring Boot configuration source) unless you’ve already enabled the resource chain via other properties or by including `webjars-locator` on the classpath.

This will automatically rewrite `@{/assets/filename}` URLs in Thymeleaf templates to include the digest in production mode (regardless of the value of `skipNonDigests`), and this will leave them alone in development mode.

In fact, if you don’t add any other resource resolvers to the resource chain in `addResourceHandlers`, it should be safe to delete the code in `AssetResolver` that delegates to the chain.

**Comment by davydotcom** [comment]
very nice !

**Comment by davydotcom** [comment]
added to spring boot plugin with the appropriate @author descriptor. Thank you for the contribution!

**Comment by lionding2009** [comment]
@astiob it's better to change registry.addResourceHandler("/assets/*") to registry.addResourceHandler("/assets/**") otherwise sub folder won't work

**Comment by xGregor** [comment]
I've seen, that the class has been removed in commit [19fde2167815ff646c7931349c0b7b92e8e3a8ba](https://github.com/bertramdev/asset-pipeline/commit/19fde2167815ff646c7931349c0b7b92e8e3a8ba).
Is there an other way to work with digest in Thymeleaf?

**Comment by mkobel** [comment]
I just created a simple taglib to use the digest urls. Details: https://github.com/bertramdev/asset-pipeline/issues/61#issuecomment-471577104
