### ISSUE TITLE
require_tree does not seem to work with recommended directory structure

### ISSUE THREAD

**Issue by mampcs** [bertramdev/asset-pipeline#134]
I have the following directory structure (using grails 2.5):

<pre>
grails-app
    assets
        javascripts
              js1.js
              js2.js
        stylesheets
        manifests
             manifest1.js
             manifest2.js
        lib
             libdir1
                 lib11.js
                 lib12.js
             libdir2
                 lib21.js
                 lib22.js
</pre>

And my manifest1.js has the following:
<pre>
//=require js1.js
//=require_tree libdir1
</pre>

With this, it's unable to find the libdir1 and it's files. The minified file only contains js1.js contents.
If i try to change the require_tree to ../lib/libdir1, then it finds the files but throws an exception:
<pre>
java.lang.RuntimeException: File was not sourced from the same ScanDirectory /home/test/example/grails-app/assets/lib/libdir1/lib11.js scanDir: /home/test/example/grails-app/assets/manifests
</pre>

Going thru the code in DirectiveProcessor.groovy, i see that the requireTreeDirective function is called with the FileSystemAssetResolver for the manifests fileSpec, which is only going to look for files under manifests directory.

I'm at a loss to figure out how this is supposed to work. Any help would be highly appreciated.

**Comment by davydotcom** [comment]
Require tree only works in the same organizational directory. If you would like it to span all resolvers use 'require_full_tree'

**Comment by mampcs** [comment]
Thank you very much. That did the trick.
