### ISSUE TITLE
Gradle plugin: different configurations for different directories

### ISSUE THREAD

**Issue by TomDmitriev** [bertramdev/asset-pipeline#135]
I want to set properties such as skipNonDigests, enableSourceMaps, etc. to different values depending on which directory the processed files come from. Is there a way to do that?

**Comment by davydotcom** [comment]
only way to do that is to use separate projects in gradle at this time. You should almost always use digested asset names anyway as its silly not to these days. sourceMaps i could see being easily modified comparatively to the other option

**Comment by TomDmitriev** [comment]
Thanks for clearing that out. I kind of supposed that it works this way. To clarify, my case was that I had a mix of resources, some of which were external libraries such as ckeditor which has its own way to manage versions, all residing in one directory. In my war file I wanted to have _only_ digested versions of some of the resources and _only_ original, non-digested versions of the others, e.g. ckeditor. I solved the problem by setting `skipNonDigests = false` and then excluding the unwanted files in `war.eachFile`.
