### ISSUE TITLE
Non-digested files not built when no source has changed but skipNonDigests has been disabled

### ISSUE THREAD

**Issue by astiob** [bertramdev/asset-pipeline#136]
1. Run `gradle clean`.
2. Set `skipNonDigests = true` in `build.gradle`.
3. Run `gradle assetCompile`. Assets are compiled to files with digests in file names.
4. Set `skipNonDigests = false` (or simply remove the assignment, as this is the default).
5. Run `gradle assetCompile`. Asset Pipeline thinks it’s already done, and nothing happens. Instead, it should create files without digests in file names.

In case this matters, I’m trying this in a Spring Boot setup.

**Comment by davydotcom** [comment]
try assetClean first

**Comment by davydotcom** [comment]
ah I see what you are saying , yea we need to change how we deal with the manifest burn file and actually embed configuration hash as well

**Comment by davydotcom** [comment]
fix coming in 2.12.2
