### ISSUE TITLE
Vary: Accept-Encoding is sent even when no gzipped version available

### ISSUE THREAD

**Issue by astiob** [bertramdev/asset-pipeline#138]
Gzipped assets can be disabled at build-time (and it is possible that they are built but unavailable at run-time due to a bug, as in #137, or a misconfiguration). Yet AssetPipelineResponseBuilder [always sets](https://github.com/bertramdev/asset-pipeline/blob/master@%7B2016-12-19%7D/asset-pipeline-core/src/main/groovy/asset/pipeline/AssetPipelineResponseBuilder.groovy#L27) the `Vary: Accept-Encoding` HTTP header, implying that a compressed version of the content is available.

At best, this is annoying, but I can imagine this harming shared caches. Additionally, in my tests with Spring Boot, Tomcat and `server.compression.enabled=true`, when Tomcat applies its own compression, it appends another `Accept-Encoding` to the header, producing `Vary: Accept-Encoding,Accept-Encoding`. I don’t know if this is valid, but in any case this seems quite pointless and ugly.

The header should only be set if the filter is actually able to find and serve the gzipped version of the requested asset.

**Comment by davydotcom** [comment]
that does not necessarily imply a gzip version is available at the current time. It does however imply that there is a possibility of this changing at some point in time, therefore it is important to set this up in the event assets are used with no digest names as well
