### ISSUE TITLE
Application does not start with Spring Boot 1.5.1: ClassNotFoundException FilterRegistrationBean

### ISSUE THREAD

**Issue by simonrleung** [bertramdev/asset-pipeline#145]
Error: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.FilterRegistrationBean

It has been moved to another package: http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/web/servlet/FilterRegistrationBean.html

**Comment by davydotcom** [comment]
Those bastards!

**Comment by bjfr** [comment]
Fixed with Pull Request https://github.com/bertramdev/asset-pipeline/pull/150 which has been merged inte master.

@davydotcom Do you think that you could release a new version soon? As it is now, asset-pipeline is broken for those who run Spring Boot 1.5 and above.

**Comment by davydotcom** [comment]
2.13.2 release

**Comment by lionding2009** [comment]
thx a lot, that saves me.
