### ISSUE TITLE
Does not support Spanish messages with accents

### ISSUE THREAD

**Issue by gasparmedina** [bertramdev/asset-pipeline#153]
Hello, I have the following problem, I have messages defined with accents in Spanish, but when I try to get the message in the following way $ L (codei18n), the message comes with strange characters, but without the accent.

The original message is "Por favor, escribe una dirección de correo válida."
But I'm getting the following. "Por favor, escribe una direcciÃ³n de correo vÃ¡lida."

I'm working on a web app with grails 2.3.11 with the plugin version
Compile ": i18n-asset-pipeline: 1.0.6"

Is this supported in the plugin?
I have already tried several solutions but without success, for example, put the character with the accent in hexadecimal, in ASCCI format and others, also use escape in javascript, but it does not work either.

Can you help me?

Thank you

**Comment by davydotcom** [comment]
Look into using the `//=encoding` directive pattern

http://www.asset-pipeline.com/manual/index.html#directives
