### ISSUE TITLE
Es6Processor writes out goog/base.js to every asset file processed

### ISSUE THREAD

**Issue by amcclain** [bertramdev/asset-pipeline#154]
We are using the ES6 transpilation support in our projects for the new ES6 syntax, etc. We are not using requires() and modules, however, and turn that support off via the `commonJs=false` config.

However we are seeing that as of aaaedb3a1e94efcf1e4bc210719c7cd1c300f393 ES6 mode is now doing extra processing that appears related to modules, as well as writing out the contents of goog/base.js for each file processed (see [here](https://github.com/bertramdev/asset-pipeline/blob/master/asset-pipeline-core/src/main/groovy/asset/pipeline/processors/Es6Processor.groovy#L132)).  As a result we are getting the contents of base repeated for each file, as well as a call made by base.js to the non-existent file deps.js.

Not sure if this is intentional - possibly a matter of the ES6Processor assuming that in ES6 mode you will only process one primary file and include all others via requires references? Should this class also check the commonJs flag and revert to the prior "light-touch" compilation (or something like that)?  

Thanks for any insight as always.

**Comment by lbwexler** [comment]
Hi -- Any thoughts on this one?

**Comment by davidkron** [comment]
I'm seeing this behavior aswell. Es6Processor really seems to expect only a single entry-point javascript file.

I think there should be an option to make this configurable and completely disable the inclusion of **asset/pipeline/goog/base.js** and **asset/pipeline/goog/es6_runtime.js**.

**Comment by davydotcom** [comment]
we switched to babel for ES6 and its waaayyy better. this is no longer an issue.
