### ISSUE TITLE
Image Expires Tag

### ISSUE THREAD

**Issue by barcelona23** [bertramdev/asset-pipeline#156]
small question, I'm getting this message "Your site is not using expires headers for your images. An expires tag can help speed up the serving of your webpages for users that regularly visit your site and see the same images."

http://jeremy.zawodny.com/blog/archives/009272.html

Is there any way to add this ?

**Comment by davydotcom** [comment]
We use cache busting with digests instead

**Comment by barcelona23** [comment]
what about Cache-Control??? Can I define Cache-Control to the images?

![image](https://cloud.githubusercontent.com/assets/221474/25724255/87fd4e30-30d8-11e7-88f2-721626786d2b.png)
