### ISSUE TITLE
[asset-pipeline-springboot] unmatched springboot 1.5.x resource path

### ISSUE THREAD

**Issue by leewin12** [bertramdev/asset-pipeline#158]
Hi, thank you for creating asset-pipeline.
I am using it since grails 2.3.

Now I am trying to apply it to a project based on springboot 1.5.2.
In there, default resoure path is `src/main/resources/static`,
but asset-pipeline-springboot looks for 
```
src/main
META-INF/assets
META-INF/assets.list
META-INF/static
META-INF/resource
```
the spring's default resource path is also using for static resource reloading in case of running application by `bootRun` (http://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html#build-tool-plugins-gradle-running-applications)
I guess I could config extra the sourceSets configuration to avoid this problem (not confirm yet)

but it would better be:
- add default path to above list
- put some comment for `releadable resource in bootRun` on manual
- add a path option on gradle asset-pipeline config and reading it

I am not sure which solution would be better.

**Comment by davydotcom** [comment]
In development mode you want to use src/assets for asset-pipeline assets.

It is important to remember spring boot doesn’t do well with asset handling and also handles static asset organization differently so you don’t want it to class with src/main/resources/static..

Make sure you are using the asset-pipeline-spring-boot plugin as it will handle automatic reloading as well just like it does in grails

**Comment by leewin12** [comment]
Thank you for answer.

This problem is not only related using spring-reloaded but also spring-boot-gradle plugin.
As far I know, spring-boot-gradle plugin detects changes of static files in sourceSets.res ( default: `src/main/resource/static` ), spring-reloaded cares only classes.

**Comment by leewin12** [comment]
detecting changes without extra config `sourceSets.main.resources`  works fine.

**Comment by leewin12** [comment]
detecting changes without extra config `sourceSets.main.resources` works fine.

**Comment by leewin12** [comment]
I did some test and now I understand @davydotcom said.detecting changes without extra config `sourceSets.main.resources` works fine, even without `bootRun.addResources`.
My concern was useless.
Thank you for you exp

**Comment by leewin12** [comment]
I did some test and now I understand @davydotcom said.
detecting changes without extra config sourceSets.main.resources works fine, even without bootRun.addResources.
My concern was useless.
Thank you for you explain and making a awesome project.

**Comment by davydotcom** [comment]
haha no worries. I try to make it so it just works for you :).

I hope you enjoy the plugin!
