### ISSUE TITLE
Proper way to discover filename

### ISSUE THREAD

**Issue by mystdeim** [bertramdev/asset-pipeline#159]
I want use your plugin in production, but I'm a little bit confused how to discover file name.
For example I have sth like `<script src="application-dfdasfdsaf4r43fs.js">` in my layout.
Should I read manifest.properties file first, find filename there then add filename to my layout?

**Comment by davydotcom** [comment]
this GSP or what template library you using?

**Comment by davydotcom** [comment]
there are grails taglibs for this. please seek documentation. you can also examine a file on the class path called `manifest.properties` to find the aliases.
