### ISSUE TITLE
asset storagePath

### ISSUE THREAD

**Issue by barcelona23** [bertramdev/asset-pipeline#164]
How can I change the permissions for storagePath?
I'm using tomcat 8.5, and it's copying the files with 640 permissions.

 I got this error on the browser. 
> Failed to load resource: the server responded with a status of 403 (Forbidden)

I have to change manually the permission each deploy.

`grails:
    assets:
    url: https://cdn.domain.com/
    storagePath: /opt/domain/assets/`

**Comment by davydotcom** [comment]
thats new, I can look into that

**Comment by davydotcom** [comment]
fixed for next release 2.14.4
