### ISSUE TITLE
Plugin assets affected by application Gradle excludes

### ISSUE THREAD

**Issue by timbonicus** [bertramdev/asset-pipeline#165]
I'm converting an application from Grails 2.5.4 to Grails 3.2.8; in the process, I moved my asset-pipeline include/exclude configuration from BuildConfig to a Gradle assets configuration:
```
assets {
     minifyJs = true
     minifyCss = true
     excludes = ["**/*.less"]
     includes = [
         "app.less",
         ...
     ]
}
```
The plugin itself has its own assets configuration:
```
assets {
     packagePlugin = true
     minifyJs = true
     minifyCss = true
     excludes = ["**/*.less"]
     includes = [
         "plugin.less",
         ...
     ]
}
```

In Grails 2.5.4, both app.css and plugin.css appeared in the generated WAR. In Grails 3.2.8, the app excludes seems to supersede the plugin declarations, causing only app.css to appear in the WAR file.

Is there something I'm missing, or is this expected? The list of LESS files for the plugin is longer than indicated here, so it's a shame that my application Gradle configuration has to know about the list to include all the plugin assets in its own includes.

Grails version: 3.2.8
Asset-pipeline Gradle version: 2.13.1

**Comment by davydotcom** [comment]
final plugin packaging is reserved for happening at the app level not the plugin level so includes excludes are not effective here
