### ISSUE TITLE
Asset compilation error with symlinks: File was not sourced from the same ScanDirectory

### ISSUE THREAD

**Issue by timbonicus** [bertramdev/asset-pipeline#166]
I have some symlinks in my project to wire up Git submodule directories:
```
assets
    javascript
         leaflet (symlink) -> submodules/leaflet/src/js
submodules
    leaflet
         src
              js
```
The assetCompile Gradle task fails with an error:
```
Caused by: java.lang.RuntimeException: File was not sourced from the same ScanDirectory /var/jenkins_home/jobs/app-deploy/workspace/submodules/leaflet/src/js scanDir: /var/jenkins_home/jobs/app-deploy/workspace/grails-app/assets/javascripts
```

This is due to FileSystemAssetResolver.relativePathToResolver using .canonicalPath, which resolves the symlink. Is it possible to switch this to use .absolutePath instead, or would that break file resolution in other ways?

**Comment by davydotcom** [comment]
That would break path normalization issues

**Comment by davydotcom** [comment]
Believe I have sorted this issue using path resolution from java 7 Path api

**Comment by davydotcom** [comment]
Will be in 3.0.2
