### ISSUE TITLE
Processing html templates in JS sources

### ISSUE THREAD

**Issue by adrianbk** [bertramdev/asset-pipeline#168]
Hi,

There are various issues and questions around how to process html templates in JS sources, specifically for AngularJS. The most sensible solution seems to be the [angular-template-asset-pipeline plugin](https://github.com/craigburke/angular-template-asset-pipeline) however, injecting the template source directly into `$templateCache` isn't quit suitable for the current project I'm working on. So, I've written a [processor](https://gist.github.com/adrianbk/6cc7916996937dcbe99360cca62fc740) to do the digested URL replacement. We were bitten by cached assets in production (non digested angular template urls) so this processor will throw an exception during pre-compilation which is ideal for our current situation. The processor pattern matches on `.htm` and `.html` allowing for optional sub extensions like `.tpl.html`.  In testing the processor I've hit a snag and haven't been able to track down the cause of this [failing test](https://gist.github.com/adrianbk/6cc7916996937dcbe99360cca62fc740#file-angulartemplatejsprocessorspec-groovy-L123) where the `AssetResolver`s cannot resolve the asset for a digested url when the asset is `.html` as opposed to `.tpl.html` i.e. the same test passes for a `.tpl.html` asset. The strange thing is: when I run `grails asset-precompile` the correct digested urls, for `.html` assets end up in the `manifest.properties` and that digested asset is also present in the output directory. Is there something or another processor eagerly creating the digested assets for html assets with a sub extension (`.tpl.html`) assets so they can be resolved by the `AssetResolver`s?

__plugin version:__ `:asset-pipeline:2.14.1`
__grails version:__ `2.5.6`

**Comment by davydotcom** [comment]
There is an HtmlAssetFile definition that runs url replacement automatically for other assets. May want to check into this. This is newer to grails3 though.
