### ISSUE TITLE
Closure Compiler Documentation Link

### ISSUE THREAD

**Issue by sdelamo** [bertramdev/asset-pipeline#170]
When disussing

grails.assets.minifyOptions

The documentation says: 

> Above are the default values for the majority of Closure Compiler. For specifics on what these options do please refer to the documentation for Closure Compiler.

Could you please provide me with a link to Closure Compiler documentation. I don't mind adding the link to the docs in a pull-request.

**Comment by andreperegrina** [comment]
I think they use this documentation: [Link](https://developers.google.com/closure/compiler/docs/compilation_levels)
I hope this help you.
