### ISSUE TITLE
Less files not being processed

### ISSUE THREAD

**Issue by sdelamo** [bertramdev/asset-pipeline#173]
I have a Grails 3.3.0 app, asset-pipeline version 2.14.3

I add Asset-Pipeline as build script dependency: 

https://github.com/grails/grails3-plugins/blob/master/build.gradle#L8

I apply the plugin: 

https://github.com/grails/grails3-plugins/blob/master/build.gradle#L26

I apply the ASSET-PIPELINE, LESS and handlebars dependencies:

https://github.com/grails/grails3-plugins/blob/master/build.gradle#L36

When I run `./gradlew assemble.`

The *.less files are not processed into CSS files

That it is to say, I have:

`build/asset/app/color.less`

instead of: 

`build/asset/app/color.css`

Am I missing anything?

**Comment by davydotcom** [comment]
are you using it for plugin development. if so you dont want them processed in the plugin, you want them only processed in a final application.
