### ISSUE TITLE
how to add custom folder.

### ISSUE THREAD

**Issue by daring123** [bertramdev/asset-pipeline#174]
Hi:
   I don't want to put some javascript files into grails-app/assets/javascripts. I want to put them in views folder .
   How do I do ?
   
![image](https://user-images.githubusercontent.com/5986074/29114568-55d5536c-7d27-11e7-9088-475cfd9eb9d0.png)
  

  This is where I  want to put some javascript files.

![image](https://user-images.githubusercontent.com/5986074/29114675-977b5992-7d27-11e7-9d54-ad77a85cdfcd.png)
  Thanks.

**Comment by davydotcom** [comment]
This violates Grails convention not sure what your doing this for

**Comment by daring123** [comment]
I  want to use Vue to write the front end.It can be clear to put javascript file in the views folder.

**Comment by pmamatsis** [comment]
Hi to everyone,
   i also wanted to do this kind of thing. I have a case into which i want to put a JS file into the view folder. Imagine a case for which for every view there is a JS file which accompanies it and into which we are placing the various business logic for the front-end as a JS object.

Is there any way for this kind of feature to be added? Can i do anything to help? If yes please point to me the way. I would be really glad to help out.

Best regards and thank you in advance,
Panos.

**Comment by davydotcom** [comment]
you can do `grails-app/assets/views` if you want.
