### ISSUE TITLE
silent failure is uncool

### ISSUE THREAD

**Issue by ScottIngram** [bertramdev/asset-pipeline#181]
//= require this-file-does-not-exist

will silently fail to include this-file-does-not-exist.js -- it should at the very least log.debug("some message")

**Comment by davydotcom** [comment]
not sure what version you are on but check out `DirectiveProcessor#requireFileDirective() LINE 281` There is a log warning for this.

[!code sample](http://bertram.d.pr/YtjnBb+)

**Comment by chrisbrookes** [comment]
I guess it's not completely silent, but it doesn't fail the Gradle build. An option to fail the build in this case might be a good idea?
