### ISSUE TITLE
ignores head tag and layoutHead

### ISSUE THREAD

**Issue by ScottIngram** [bertramdev/asset-pipeline#182]
When rendered via a `<g:include>`, the `<asset:javascript>` and `<asset:stylesheet>` do not care if you put them inside your `<head>` block.  Nor do they care if you use the `<g:applyLayout>` to render a layout that does NOT include a `<g:layoutHead>`, it's going to render regardless.

I've struggled to find a satisfactory solution to writing components that can be rendered both in isolation (myApp/widgets/one) and in aggregate (myApp/allWidgetsWorkbench).  The aggregation fails when the components share overlapping dependencies.  Or, after removing the dependencies declaration from the components, they fail to work in isolation.  I had been able to employ this layouts strategy using the Resources plugin, but not in Asset Pipeline.

**Comment by davydotcom** [comment]
not advised to use asset-pipeline this way. it is best to bundle all assets in one master manifest and use init methods that check things like the data-page attribute of the body or body class. You can then better bundle your assets and get more efficient load times that get cached under one digest
