### ISSUE TITLE
[Spring Boot] Assets not being served with standalone Tomcat server

### ISSUE THREAD

**Issue by SHININGU** [bertramdev/asset-pipeline#183]
I'm currently using Spring Boot 1.5.7 with asset-pipeline-gradle:2.6.7, everything works just fine when running the Spring Boot embedded server, but when I want to deploy a war on a real Tomcat 8 server, every asset request returns 404 (the server seems to work fine since I can open my login page but with no CSS or JS).
I have my assets folders (javascript, stylesheets, etc) on the standard src/assets folder, I figure there's a little bit of configuration I'm missing for deploying a war but I can't find anything.

**Comment by davydotcom** [comment]
thats a bit of an old version . any reason you aren't using a newer asset-pipeline?

**Comment by davydotcom** [comment]
think this is resolved in 2.14.4
