### ISSUE TITLE
Grails 3.2.11 in multi projet setup, plugin's asset are not reference in GSP with cached digest name 

### ISSUE THREAD

**Issue by runwolf** [bertramdev/asset-pipeline#184]
Grails version: 3.2.11
Groovy version: 2.4.11
JVM version: 1.8.0_144
assetPipeline - 2.14.3
Deploy as a war in tomcat 8

I have a project build with the sub project structure and I am using grails 3.2.11.
All my asset get package and deliver properly for the main project using the cache-digest names.
But if I call a controller in a plugins that's package with my main project, I can see the compile version of the asset with the digest name but the gsp still call the original asset name, no digest.
If the plugins reference asset in my main project, it gets the digest version.

Problem is some browser seem to cache those files and don't get the new versions some time.

Is this a configuration issue or there is an issue with asset-pipeline ?

**Comment by davydotcom** [comment]
probably not using packagePlugin feature to properly package assets from the source plugin.  Theres a flag you should put in your build.gradle for your plugins in the `assets{}` block called `packagePlugin = true`

http://www.asset-pipeline.com/manual/index.html#configuration

This tells asset-pipeline not to precompile these assets in the plugin and leave them free to be bundled via the final application manifest.
