### ISSUE TITLE
[Grails plugin] AssetPipelineFilter does not return Gzip encoding to Safari using HTTPS

### ISSUE THREAD

**Issue by CJKirkby** [bertramdev/asset-pipeline#185]
After enabling GZIP encoding on a project, and confirming that .gz files were being generated and included in the WAR file, "gzip" encoding was not used for assets when testing my web app over HTTPS in Safari. "gzip" encoding _was_ used when testing my app in Chrome.

I tracked down the cause to be the "Accept-Encoding" header passed in the request from Safari. In recent versions, the value of this header is `"br, gzip, deflate"` when requesting assets on HTTPS. The gzip test in `AssetPipelineFilter` returns false for this value:

```
acceptsEncoding?.split(",")?.contains("gzip")
``` 

as the split value contains `" gzip"`, not `"gzip"`

This affects:
- Safari on macOS - Version 11.0.1 (13604.3.5) (no other versions tested)
- Safari on iOS 11
- WKWebView on iOS 11

Both Safari and WKWebView on iOS 10.3.1 send request header "Accept-Encoding" as `"gzip, deflate"` and receive gzipped content encoding.

**Comment by CJKirkby** [comment]
Just reviewing the changes on the `brotli` branch, and wanted to point out that you may encounter a similar issue here as well. Chrome appears to send it's "Accept-Encoding" header value as `gzip, deflate, br`, so the space needs to accounted for in the `contains("br")` condition.

**Comment by davydotcom** [comment]
well this explains a lot, good call!

**Comment by davydotcom** [comment]
fixing in 2.14.5, also redoing brotli a bit, going to make content-encoding pluggable
