### ISSUE TITLE
Grails Asset Pipeline keeps open connection for null asset (Tomcat 7, secure connection)

### ISSUE THREAD

**Issue by ilPittiz** [bertramdev/asset-pipeline#189]
I have a Grails 3 web-app, running on Apache Tomcat 7 server with default configuration (configuration details below).

I observed something unexpected when requesting a null asset (i.e. an asset with null path), e.g. `http://tomcatServer/assets/`.
In this case the response body is a processed Grails view, returned with 404 status in a matter of milliseconds. And that might be ok, even though maybe it'd be better to have empty response body.
The unexpected part comes when loading the same url in https (Tomcat 7 default configuration has a default connectionTimeout of 60 seconds): the same processed page (as response body) is returned immediately, but the connection is left open until connection timeout occurs for a total of 60 seconds.

I'm aware this scenario has no real use case, but it means that single requests might take one connection each busy for 60 seconds, and this might be used maliciously to saturate the server connections pool.

### Example

You can find a very simple application as example [here](https://github.com/ilPittiz/nullAsset).
When deploying it on Tomcat 7 you'll notice:
- load bundled asset: both urls serve the image resource as expected (in a matter of milliseconds)
  - http://tomcatServer/assets/boogie.gif
  - https://tomcatServer/assets/boogie.gif
- load non-existent asset: both urls respond with 404 status as expected (in a matter of milliseconds)
  - http://tomcatServer/assets/fake.jpg
  - https://tomcatServer/assets/fake.jpg
- load null asset
  - http://tomcatServer/assets/ -> returns HTML page (processed grails view) with 404 status (in a matter of milliseconds)
  - https://tomcatServer/assets/ -> returns HTML page (processed grails view) as response body, but the connection is left open until connection timeout occurs.

### Configuration
- Grails 3.2.6 (Gradle 3.5.1)
- Grails Asset Pipeline plugin: 2.14.6
- Server version: Apache Tomcat/7.0.78
- JVM version: 1.8.0_131

**Comment by davydotcom** [comment]
Very interesting however this seems like a tomcat issue and not an asset pipeline issue as we don’t do anything different on ssl vs non ssl..

**Comment by ilPittiz** [comment]
Upgrading to a more recent Tomcat version (specifically 8.5.24) is already on my TODO list, but unfortunately it won't happen very shortly. However I'll let you know what I find once I get there.

On another matter, about the different response body between `/assets/fake` (no content) and `/assets/` (processed Grails view+layout, result below from my example on Github), wouldn't it be better to have blank content for the latter as well?

```<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>Page Not Found</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="layout" content="main">
</head>
<body>
    <ul class="errors">
        <li>Error: Page Not Found (404)</li>
        <li>Path: /assets/</li>
    </ul>
</body>
</html>
```

**Comment by ilPittiz** [comment]
Quick update: upgrading the server to Tomcat 8.5.24 (same default configuration) didn't solve the issue.
Something I didn't point our earlier, maybe it's somehow helpful: when running my Grails application locally (with embedded Tomcat) the issue doesn't occur, as all connections seem to be closed as expected as soon as the response body is returned.

**Comment by davydotcom** [comment]
can you try this with 2.14.7 asset-pipeline

**Comment by ilPittiz** [comment]
Thanks, I confirm the issue is now fixed!
Tested on both Tomcat 7 and 8.5, and everything works as expected.
