### ISSUE TITLE
WAR packaging error: Inconsistent stackmap frames

### ISSUE THREAD

**Issue by jbelis** [bertramdev/asset-pipeline#191]
Hi,

I am using grails 2.5.4, jdk 1.8 (openjdk-8-jdk:amd64 8u102-b14.1-1~bpo8+1) on Debian 3.16.39-1+deb8u2

I get the following error at war creation : 
`
grails  war --non-interactive --plain-output --stacktrace --verbose --refresh-dependencies
...
|Processing File 35 of 272 - fonts/fontawesome-webfont.woff2
|Processing File 36 of 272 - fonts/fontawesome-webfont.svg
|Processing File 37 of 272 - optin/app/izicap-tpe/services/garbage.js
|Processing File 38 of 272 - optin/app/izicap-tpe/services/notifier.js
   [delete] Deleting directory /srv/jenkins-slave/workspace/staging.back/target/work/stage
|Processing File 39 of 272 - optin/app/izicap-tpe/services/user-data.js
.
|Processing File 40 of 272 - optin/app/izicap-tpe/services/route-mapper.js
Error |
WAR packaging error: Inconsistent stackmap frames at branch target 30
Exception Details:
  Location:
    com/google/javascript/rhino/JSDocInfo.getMarkers()Ljava/util/Collection; @30: areturn
  Reason:
    Type 'com/google/common/collect/ImmutableList' (current frame, stack[0]) is not assignable to 'java/util/AbstractCollection' (stack map, stack[0])
  Current Frame:
    bci: @20
    flags: { }
    locals: { 'com/google/javascript/rhino/JSDocInfo' }
    stack: { 'com/google/common/collect/ImmutableList' }
  Stackmap Frame:
    bci: @30
    flags: { }
    locals: { 'com/google/javascript/rhino/JSDocInfo' }
    stack: { 'java/util/AbstractCollection' }
  Bytecode:
    0x0000000: 2ab4 0009 c600 0d2a b400 09b8 0056 c700
    0x0000010: 09b8 009c a700 0a2a b400 09b8 0056 b0  
  Stackmap Table:
    same_frame(@17)
    same_frame(@23)
    same_locals_1_stack_item_frame(@30,Object[#569])

Build step 'Build With Grails' marked build as failure
`
My BuildConfig.groovy includes the following:

`
grails.project.dependency.resolution = {
   ...
    plugins {
        // plugins for the build system only
        build ":tomcat:7.0.70"

        // plugins for the compile step
        compile ":scaffolding:2.1.2"
        compile ':cache:1.1.8'
		compile ':marshallers:0.6'
		compile ':asset-pipeline:2.14.1'
		provided ":sass-asset-pipeline:2.14.1"
		compile ":angular-annotate-asset-pipeline:2.4.1"

        // plugins needed at runtime but not for compilation
		compile ":hibernate4:4.3.10" // or ":hibernate4:4.1.11.2"
        runtime ":database-migration:1.4.1"

        // Uncomment these (or add new ones) to enable additional resources capabilities
        //runtime ":zipped-resources:1.0.1"
        //runtime ":cached-resources:1.1"

		compile ":spring-security-core:2.0.0"
		compile ':spring-security-oauth:2.0.2'
		compile ':spring-security-oauth-facebook:0.1'
		
		compile "org.grails.plugins:quartz2:2.1.6.2"
		compile "org.grails.plugins:mail:1.0.7"
		compile ":platform-core:1.0.0"
		compile ':locale-configuration:1.1.1'
		
        compile ":rest:0.8"

		runtime ":cache-headers:1.1.7"
		runtime ':rollback-on-exception:0.2'
		compile ":codenarc:1.0"

		runtime "org.grails.plugins:cors:1.1.8"

		test "org.grails.plugins:code-coverage:2.0.3-3"
    }
}

...
grails.assets.minifyJs = false
grails.assets.minifyCss = false
grails.assets.minifyOptions = [
	optimizationLevel: 'WHITESPACE_ONLY'
]
`

I don't have this problem if I comment out the grails asset plugin.

Do you see a version incompatibility problem with my configuration?
Has anyone seen this before?

Thank you

**Comment by jbelis** [comment]
PS : this does not happen with the combination : 

		compile ':asset-pipeline:2.9.1'
		provided ":sass-asset-pipeline:2.9.1"

So it seems that something changed between versions 2.9.1 and 2.14.1 which causes this to happen. It may be a problem with the way I have set my dependencies.

**Comment by davydotcom** [comment]
Closure cant process your jsdoc in the fule it references... maybe check it
for invalid jsdoc
