### ISSUE TITLE
Excluding JS Files from minification results in non usable files within page

### ISSUE THREAD

**Issue by dtamm** [bertramdev/asset-pipeline#192]
Using the 
```
grails.assets.excludes = ["**/*Spec.js"]
```
option will result
```
<asset:javascript src="path\for\file\unitSpec.js" />
```
in 
```
<script type="text/javascript" src="/grails-application-name/assets/path/to/file/unitSpec.js" ></script>
```
which seems to be a non existing or empty file.

Excluding these files would mean to me, that i exclude them from minification but i could still use them on the page, or am i wrong here?

Using asset-pipeline version 2.14.1 on Grails 2.5.4.

**Comment by davydotcom** [comment]
no you are excluding them from inclusion and processing entirely. typically you do this for all files but application.js and register your requires in a "manifest" js file.

**Comment by dtamm** [comment]
Wow, that has been a pretty damn lag till the answer... ok got it!

**Comment by davydotcom** [comment]
Yea it got hidden in the issues list , sorry about that. Eyes kept not seeing it
