### ISSUE TITLE
AssetPipelineGrailsPlugin.groovy throws exception when application deployed to jBoss

### ISSUE THREAD

**Issue by zodiki** [bertramdev/asset-pipeline#201]
java 1.7, jboss 5.2, grails 2.4.3, assetpipeline:2.0.19

(Not a directory)
java.io.FileNotFoundException: /var/lib/jbossas/server/foo/deploy/bar.war/WEB-INF/lib/grails-core-2.4.3.jar/META-INF/grails-plugin.xml (Not a directory)
        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
        at java.util.zip.ZipFile.<init>(ZipFile.java:145)
        at java.util.jar.JarFile.<init>(JarFile.java:154)
        at java.util.jar.JarFile.<init>(JarFile.java:91)
        at asset.pipeline.fs.JarAssetResolver.<init>(JarAssetResolver.groovy:45)
        at AssetPipelineGrailsPlugin$_closure1.doCall(AssetPipelineGrailsPlugin.groovy:56)

The issue appears to be with this code:

    for(plugin in pluginManager.getAllPlugins()) {
            if(plugin instanceof org.codehaus.groovy.grails.plugins.BinaryGrailsPlugin) {
                def descriptorURI = plugin.binaryDescriptor.resource.URI
                descriptorURI = new java.net.URI( new java.net.URI(descriptorURI.getSchemeSpecificPart()).getSchemeSpecificPart()).toString().split("!")[0]

                AssetPipelineConfigHolder.registerResolver(new JarAssetResolver(plugin.name,descriptorURI,'META-INF/assets'))
                AssetPipelineConfigHolder.registerResolver(new JarAssetResolver(plugin.name,descriptorURI,'META-INF/static'))
            }

        }

for JBoss, the binaryDescriptor.resource.URI returned from the plugin is of the form vfszip:/path
rather than the expected (from the code) jar:<url>!/[<entry>] 
It seems the code doesn't determine the embedded jar path correctly for vfszip scheme URIs. This makes the plugin incompatible with JBoss deployments.

**Comment by casey1111** [comment]
I have a related issue; not sure if this needs to be a new issue or not.

With this same section of code, there is an issue related to spaces in descriptorURI.
On my Grails install on Windows, ivy-cache is under "Documents and Settings". When descriptorURI is first assigned, the spaces are correctly encoded as %20, but it seems .getSchemeSpecificPart() returns with spaces un-encoded which kills the app on startup.

(issue doesn't occur on < 2.0 versions)

**Comment by davydotcom** [comment]
Fixed in 2.1.1
