### ISSUE TITLE
update closure-compiler-unshaded

### ISSUE THREAD

**Issue by zyro23** [bertramdev/asset-pipeline#203]
manually enforcing `v20180402` with asset-pipeline-2.14.10 (gradle) seems to work fine for me.
needed this to avoid some "unknown variable" `$$$0` error during minification (uglyfication).

**Comment by zyro23** [comment]
now tried with 3.0.0 and `v20180506` and took a look at the code. i guess the problem is the `LanguageMode` mapping:
* https://github.com/bertramdev/asset-pipeline/blob/master/asset-pipeline-core/src/main/groovy/asset/pipeline/processors/ClosureCompilerProcessor.groovy#L103-L117
* https://github.com/google/closure-compiler/blob/v20180506/src/com/google/javascript/jscomp/CompilerOptions.java#L3021-L3063

n.b. seems 3.0.0 is released but not tagged yet.

**Comment by davydotcom** [comment]
closure is missing some pluggable ES2017 resolver stuff so they have to fix that before we can upgrade it... we switched to babel on a lot of stuff though so may be able to push on this.
