### ISSUE TITLE
Error while war packing

### ISSUE THREAD

**Issue by dmaklock** [bertramdev/asset-pipeline#205]
Packing crashes with next error:
>>Error WAR packaging error: Could not find matching constructor for: asset.pipeline.DirectiveProcessor(java.util.ArrayList, asset.pipeline.AssetCompiler)

**Comment by davydotcom** [comment]
This error happens if you are running a pre 2.0 compatible asset pipeline extension what plugins do you have setup?

**Comment by dmaklock** [comment]
Yes, I'm using ":less-asset-pipeline:2.0.8" plugin also. 
If I remove temporarily this plugin (less-asset-pipeline), building will ok. But this conflict in packing began after ":asset-pipeline:2.0.20" version

**Comment by davydotcom** [comment]
Releasing 2.1.0 should be fixed. was a bug if you have @import directives or reference other css files in a url() in a css file
