### ISSUE TITLE
improve intellij support

### ISSUE THREAD

**Issue by domurtag** [bertramdev/asset-pipeline#206]
IntelliJ has really good support for the resources plugin. For example, when you select a module in `AppResoures.groovy` and run "Find Usages" it will find all GSPs where that module is used. Also any text inside a block such as
````
<r:script>
initPage('${request.contextPath}');
</r:script>
````
is recognised as JavaScript, so you can ctrl+click on `initPage` and it will jump to the definition of that function.

There doesn't seem to be equivalent support for the asset-pipeline plugin (at least not in IntelliJ v. 13.1.6). For example, if I define a block
````
<asset:script>
initPage('${request.contextPath}');
</asset:script>
````
The contents are treated as plain text, rather than JavaScript.

I'm not sure where IntelliJ's support for the resources plugin comes from. If there is something included in the resources plugin itself that provides it, then presumably a similar something could be included in the asset-pipeline plugin.

On the other hand, if the resources plugin support is baked into IntelliJ itself, then it seems there's not much that can be done other than to encourage the IntelliJ devs to bake in similar support for asset-pipeline.

**Comment by davydotcom** [comment]
I think you have to wait for the IntelliJ guys on this one

**Comment by domurtag** [comment]
> I think you have to wait for the IntelliJ guys on this one

Perhaps, but IntelliJ does provide [a mechanism for you to extend it's understanding of DSLs](http://confluence.jetbrains.com/display/GRVY/Scripting+IDE+for+DSL+awareness), and I'm wondering if the resources plugin somehow used this.

If not, then at least we should open an issue in the IntelliJ bug tracker asking them to support asset-pipeline similarly to resources.

**Comment by hansgru** [comment]
@domurtag  There doesn't seem to be a "resources" IntelliJ plug-in, but the functionality seems to be in the "grails" plug-in that doesn't seems to be open source at all (like the groovy plugin).
