### ISSUE TITLE
Files in subdirectories are not included

### ISSUE THREAD

**Issue by TimDMeyer** [bertramdev/asset-pipeline#207]
Hello

I have a little problem since my update from 1.9.9 to 2.0.21 or 2.1.0.

Before I excluded everything with grails.assets.excludes = ["*/**"], then I included every file I need, like this: 

```
grails.assets.includes = [
    "others/font-awesome/font/FontAwesome.otf", 
    "others/font-awesome/font/fontawesome-webfont.*", 
    "others/pdfJS.js", 
    "others/pdf/pdf.worker.*",
    "login.*",
    "register.*",
    ...
]
```
This worked just fine in 1.9.9, but now every file in a subdirectory is not picked up, while compiling.
So the files: pdfJS.js, login.js, login.less, register.js, register.less are all handled, the other ones are not.

Tim

**Comment by davydotcom** [comment]
Fixed in 2.1.1
