### ISSUE TITLE
On complete event?

### ISSUE THREAD

**Issue by davemiranda** [bertramdev/asset-pipeline#211]
I'm working on a Grails web application and want to define reusable RequireJS modules in a Grails plugin so that modules in the web application can depend on them.  The problem is that the RequireJS optimizer needs all modules to be in the same base directory and with the this approach, some modules are in the web application and others are in the plugin.

The asset pipeline solves this problem because it puts all the JS from plugins into the web application target assets directory just before war creation. If I can determine when asset pipeline finishes, I can run the optimizer.

What are your thoughts on creating an "on complete" event that people could hook into to run additional scripts?

**Comment by ctoestreich** [comment]
@davemiranda I know you already have this ready for a pull request.  Send a PR and let @davydotcom review the change so we can start using this asap!

**Comment by davemiranda** [comment]
Submitted pull requests #212 and #213 with proposed changes.

**Comment by davemiranda** [comment]
An example project that would use this event:

https://github.com/Grails-Plugin-Consortium/requirejs-grails-asset-pipeline

After asset precompile, it runs the RequireJS optimizer for modules in the assets directory.  It also replaces asset-pipeline generated JS modules (.js,.js.gz,-digest.js,-digest.js.gz) with their RequireJS-optimized counterparts and updates the asset-pipeline manifest with the new digests.

**Comment by davydotcom** [comment]
hmm interesting. not sure why you might want to do it this way. It really sounds like you just want the js files to be able to be processed using r.js. This sounds more like it should be a Processor added to the JsAssetFile spec no?

**Comment by davemiranda** [comment]
Correct, I'd like to have require JS modules processed using r.js.  Your approach makes sense.

Would adding such a Processor require code changes to asset-pipeline or asset-pipeline-core?  Or does asset-pipeline already provide a way for us to do this?

**Comment by davydotcom** [comment]
The asset-pipeline is highly extensible for just this type of thing. The documentation on how to extend the asset-pipeline can be found here: 

http://bertramdev.github.io/asset-pipeline/guide/extending.html

You will notice a paragraph talking about processor.specs file. Which needs to be packaged in your plugins final META-INF/asset-pipeline directory. To do this I recommend making a META-INF folder in your grails-app/conf. Or, you can make your plugin a standard gradle extension plugin such that your plugin can be used by any framework taking advantage of the asset-pipeline. This can be posted to mavenCentral if you wanted to. An example extension plugin can be found here. https://github.com/bertramdev/coffee-asset-pipeline

Also I noticed your plugin has a build.js to determine (I assume) where its include paths are. You could potentially tie right into the asset-pipelines resolver logic to find these files like we do for LESS. the AssetHelper class in asset-pipeline-core has some methods that can be used to do this such as… AssetHelper.fileForFullName(scanPath). Everything in the Asset-Pipeline is converted to a root relative path of the resolvers. I.e. a file such as `assets/javascripts/test.js` translates to `test.js` or `assets/javascripts/handlebars/handlebars-runtime.js` to `handlebars/handlebars-runtime.js` Could make it fairly easy to tie r.js into this import logic. You can even scan for these files by content-type target. So you can even require coffee script files in. You would just ask for the `assetFile.processedStream()` If you want to even allow your required files to use the standard asset-pipeline require directives (nested). You can also run it through the directive processor. For example:

```
def processor = new asset.pipeline.DirectiveProcessor(‘application/javascript’)
def assetFile = AssetHelper.fileForFullName(filePath) // or AssetHelper.fileForUri(‘fileName’,’application/javascript’)
String result = processor.compile(assetFile)
```



--
David Estes

On January 23, 2015 at 12:19:12 AM, davemiranda (notifications@github.com) wrote:

Correct, I'd like to have require JS modules processed using r.js. Your approach makes sense.

Would adding such a Processor require code changes to asset-pipeline or asset-pipeline-core? Or does asset-pipeline already provide a way for us to do this?

**Comment by davemiranda** [comment]
What do you think of this approach:

In a RequireJS asset-pipeline plugin:

* Assign RequireJsProcessor to the JsAssetFile specs.
* In the RequireJsProcessor process method, read the build.js file (is there a better place to read this file so that we only read it once for asset precompile?) and determine if the JS file currently being processed is a RequireJS module specified in build.js.  If it is, run the optimizer for that specific file (using the other build.js parameters like baseUrl, exclusions, etc as specified in build.js).  Read the optimized file contents and return that from the processor.

**Comment by davydotcom** [comment]
Sounds like a plan. You could possibly cache your build.js file in your processor in a static def so you don’t have to reread it multiple times.
--
David Estes

On January 23, 2015 at 9:50:30 AM, davemiranda (notifications@github.com) wrote:

What do you think of this approach:

In a RequireJS asset-pipeline plugin:

Assign RequireJsProcessor to the JsAssetFile specs.
In the RequireJsProcessor process method, read the build.js file (is there a better place to read this file so that we only read it once for asset precompile?) and determine if the JS file currently being processed is a RequireJS module specified in build.js. If it is, run the optimizer for that specific file (using the other build.js parameters like baseUrl, exclusions, etc as specified in build.js). Read the optimized file contents and return that from the processor.

**Comment by davemiranda** [comment]
Thanks, I'll give that a shot and get back to you!

**Comment by davemiranda** [comment]
Do you have an example of how to add a processor to JsAssetFile using asset-pipeline 1.9.*?

It appears asset pipeline 1.9.* doesn't support processor.specs.  Using sass-asset-pipeline as an example, I added an eventAssetPrecompileStart callback that invokes a target which attempts to add the processor to JsAssetFile, however, I'm running into ClassNotFoundException on JsAssetFile (even though I listed asset-pipeline as compile time plugin in my RequireJS plugin).

**Comment by davemiranda** [comment]
Well, this seems to work...I think my issue was that I was using an import for JsAssetFile.  Is this the correct way to add a processor to JsAssetFile using asset-pipeline 1.9.*?

'''groovy
eventAssetPrecompileStart = { assetConfig ->
    def jsAssetFile = classLoader.loadClass('asset.pipeline.JsAssetFile')
    def requireJsProcessor = classLoader.loadClass('asset.pipeline.RequireJsProcessor')

    jsAssetFile.processors << requireJsProcessor
}
'''

**Comment by ctoestreich** [comment]
@davemiranda if you get the plugin working with the js processor, let me know and I will publish from the @grails-plugin-consortium repo.

**Comment by davydotcom** [comment]
AssetPrecompileComplete
