### ISSUE TITLE
Everything ends up in the war, even the content from web-apps and the contents from all plugins web-apps

### ISSUE THREAD

**Issue by langerc** [bertramdev/asset-pipeline#214]
I tried to move an angular app from a gulp (or grunt) workflow that was actually quite nice to the asset pipeline (because it fits the build process better)
I am using bower, but for the test i removed it to make it easier.

The application.js is build quite nice, everything is working in development mode. However when i try to run a grails war - things start to break.
All Files from the assets directory end up in the build target and will be minified / processed. Since some less files don't work right with the less plugin the build will fail with a broken build.
Moreover it takes ages to generate 1200 Files from all dependencies that are not required and should not be in the project.

Last but not least the content of the web-app directory is copied to target/assets too. Event the content of web-app of the plugins used ends up in target/assets during build.

Maybe i got something wrong but if i specify all the requirements with require - i dont want o have all that other crap in my build target directory. The war has hundrets of megabytes instead of 20 because of that.

So is there a way to just include the things i required in application.js and application.css?

I played arround with excludes, does not work very nice and is a lot of effort.

i tried with an empty application.js and application.css - the minified version of both files is empty and correct, however i still end up with an asset directory of 17mb with files from jquery, the content of the web-app, the content of the asset directory and so on.

any ideas?

my settings in config.groovy (i tried lots of excludes, not only this one) minification is disabled for debugging, same result without those parameters.

grails.assets.excludes = ["bower_components/*","skin/*", "bower.json", "web-app/*", "jquery/*"]
grails.assets.minifyJs = false
grails.assets.minifyCss = false
grails.assets.angular.includePathInName = true
grails.assets.bundle=false

**Comment by davydotcom** [comment]
You can also define exclude patterns at the plugin level. Remember it uses a glob pattern so **/*.js would exclude all js then you can use includes to whitelist js files
