### ISSUE TITLE
Specifying debug environment

### ISSUE THREAD

**Issue by bajormar** [bertramdev/asset-pipeline#216]
By default, asset plugin thinks that debug environment is development. However, in our project we are using 'local' environment by as the one which is used locally(it was needed because of kerberos), and development is used on development server.

It would be very good if it would be possible to pass debug application environment.

For now we have made workaround 
if(Environment.current == Environment.CUSTOM && Environment.currentEnvironment.name.equals("local")) {
   params._debugAssets = "y"
}, but it breaks after war generation

**Comment by davydotcom** [comment]
really we just need to assume non wardeployed mode is debug mode

**Comment by davydotcom** [comment]
changed for next release only looks at warDeployed
