### ISSUE TITLE
ES5 mode stops working in 3.0.2

### ISSUE THREAD

**Issue by aibolit** [bertramdev/asset-pipeline#217]
In my build.gradle I have
``` groovy
    minifyOptions = [
        languageMode: 'ES6',
        targetLanguage: 'ES5'
    ]
```
It used to minify to ES5 code in 3.0.1 and doesn't do so in 3.0.2

For example
``` es6
var test = () => {return 'hello';};
```

In 3.0.1 I get
``` javascript
//# sourceMappingURL=test.js.map
var process=process||{env:{NODE_ENV:"development"}},test=function(){return"hello"};
```

In version 3.0.2 I get
``` javascript
//# sourceMappingURL=test.js.map
'use strict';var process=process||{env:{NODE_ENV:"development"}};var test=()=>{return"hello"};
```
Notice the arrow function is not valid ES5

**Comment by davydotcom** [comment]
this functionality was removed in favor of the new native ES6 processing as part of babelJs...

Please refer to the documentation for more information on the adjustments needed

http://www.asset-pipeline.com/manual/index.html#ecmascript-2017-2018-beyond
