### ISSUE TITLE
Why deferred scripts are not recommended?

### ISSUE THREAD

**Issue by maurociancio** [bertramdev/asset-pipeline#219]
Hi there, I'm reading the docs, specifically this line:

https://github.com/bertramdev/asset-pipeline/blob/1deac5f88edd1d50fe9a03ef41a4990d8b518255/asset-pipeline-grails/src/docs/guide/usage/linking.gdoc#L63

Would you please explain why deferred scripts are not recommeded?
Thanks!

**Comment by davydotcom** [comment]
because its bad practice to do seperate js files for each page. better to do a single manifest.
