### ISSUE TITLE
Support including CSS from Javascript

### ISSUE THREAD

**Issue by ingokegel** [bertramdev/asset-pipeline#219]
Many plugins, such as fancybox have CSS that goes along with them. It would be great if CSS dependencies could be declared directly in the Javascript file.  

Currently, adding 

//=require some.css

to the Javascript file leads to this exception:

	Caused by NullPointerException: Cannot invoke method sort() on null object
	->>  150 | fileNameWithoutExtensionFromArtefact in asset.pipeline.AssetHelper
	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
	|     99 | loadRequiresForTree in asset.pipeline.DirectiveProcessor
	|     93 | loadRequiresForTree in     ''
	|     76 | getFlattenedRequireList in     ''
	|     83 | getDependencyList in asset.pipeline.AssetPipeline
	|     39 | doCall    in asset.pipeline.grails.AssetsTagLib$_closure1
    ...

**Comment by davydotcom** [comment]
Requires is used for bundling assets together of the same type. Declaring a css dependency doesn't work here as it fundamentally doesn't make sense. There is no tag lib in grails that adds both stylesheet link tags and javascript tags from the same request.

**Comment by ingokegel** [comment]
Your call, but "as it fundamentally doesn't make sense" is disputable. You could do this with the resources plugin and I found this to be a downside when migration to asset pipeline.

**Comment by davydotcom** [comment]
Except that was a separate file. Now there is a possibility that a specification or package.json type could be created in your assets and multiple requirements across content types could be defined there. That could be a possible solution.

**Comment by ingokegel** [comment]
That sounds good
