### ISSUE TITLE
Fail on asset not found

### ISSUE THREAD

**Issue by maurociancio** [bertramdev/asset-pipeline#220]
Hi there!

I'm using the following syntax:

    <asset:javascript src="app.js" />
    <asset:stylesheet src="app.css" />

I expected an error to be raised if `app.js` or `app.css` cannot be found. Is there a config I can tweak to change this behavior?

I'm on Grails 3.
Thanks!

**Comment by davydotcom** [comment]
thats not how this is supposed to work
it will make the request just like any other script or link rel tag
