### ISSUE TITLE
User should be able to configure NODE_ENV 

### ISSUE THREAD

**Issue by aibolit** [bertramdev/asset-pipeline#221]
https://github.com/bertramdev/asset-pipeline/blob/8e4faebc4e87fd1d9fa9ce435c24b2410b8859b8/asset-pipeline-core/src/main/groovy/asset/pipeline/processors/JsNodeInjectProcessor.groovy#L45

The NODE_ENV is always forced to be development and there is no way to change this at the moment. 
The value for this should be in some way configurable based off of the environment.

**Comment by davydotcom** [comment]
will be fixed in 3.0.6
