### ISSUE TITLE
More control over directive patterns

### ISSUE THREAD

**Issue by jurberg** [bertramdev/asset-pipeline#222]
I'm working on a EcmaScript 6 pipeline using [6to5](http://6to5.org) to translate the code to ES5 to run in the browser.  I wanted to have my extension read the import statement to figure out what to require rather than expecting a separate //= require statement.  For example, the following statement would cause the asset pipeline to load /app/app.es6 before this file:
```javascript
import {app} as App from '../app.es6'
```
The AssetFile only allows you to create a regex to identify directives.  I ended up with the following file definition which returned "from '../app.es6'":
```groovy
Pattern directivePattern = ~/import.*(from.*'.*').*/
```
I have not found a way to strip quotes from a regex capture, so I had to create a separate AssetResolver which extends FileSystemAssetResolver that would strip the quotes off before sending it along.

Is it possible to update the asset pipeline to call a method on AbstractAssetFile to get the directive lines from the file?  That way I could override it and remove the quotes there without having to add a custom AssetFileResolver.  Or is there a better way to accomplish what I'm trying to do?

Thanks!

**Comment by davydotcom** [comment]
Directive patterns are operated in mass on the document to dramatically speed up parsing time. As far as the use of import this looks like something that needs to be evaluated by a js runtime. You may look into doing this via a Processor on top of JsAssetFile instead

**Comment by jurberg** [comment]
I'm actually attempting to use the import statement as my 'directive'.  I'm trying to avoid duplicating every file name with both a require directive and an import: 
```javascript
//= require /app/app.es6
//= require /app/controller/HomeCtrl.es6
//= require /app/service/UserService.es6
import {App} as app from '../app.es6';
import HomeCtrl from '../controller/HomeCtrl.es6';
import UserService from '../service/UserService.es6';
```
I have this working but it's a bit of a hack.  My directive pattern looks for the import statement and pulls out the file name, but it still has the quotes in it. I have to include a separate custom FileSystemAssetResolver that strips the quotes out before processing it.  

Here is the relevant code:
```groovy
//Config.groovy
AssetHelper.assetSpecs << Es6File
DirectiveProcessor.DIRECTIVES.put('from', "requireFileDirective")
AssetPipelineConfigHolder.registerResolver(new Es6AssetFileResolver('es6', 'grails-app/assets/javascripts'))

//Es6File.groovy
class Es6File extends AbstractAssetFile {
    static final String contentType = 'application/javascript'
    static extensions = ['es6']
    static final String compiledExtension = 'js'
    static processors = [Es6to5Processor]
    Pattern directivePattern = ~/import.*(from.*'.*').*/
}

//Es6AssetFileResolver.groovy
class Es6AssetFileResolver extends FileSystemAssetResolver {
    Es6AssetFileResolver(String name, String basePath) {
        super(name, basePath, false)
    }
    AssetFile getAsset(String relativePath, String contentType = null, String extension = null, AssetFile baseFile = null) {
        relativePath = relativePath.replaceAll("'", "")
        super.getAsset(relativePath, contentType, extension , baseFile)
    }
}
```

I was hoping to find a way to do this without having to create a separate AssetResolver just to remove quotes.  Any ideas would be appreciated.
