### ISSUE TITLE
SWF file not loading correctly on FireFox

### ISSUE THREAD

**Issue by robbugh** [bertramdev/asset-pipeline#224]
Using Asset-Pipeline plugin v2.1.1
I have a flash file in ../assets/images/swf/myapp.swf that is served up to my app via the pipeline
In my gsp I use an embed tag with an AssetPth tag like so:
```
<embed src="${g.assetPath(src: 'swf/myapp.swf')}" ...etc.>
```

This works on IE 11 and Chrome v40 but on FireFox v35 it does not. Acts like the swf is damaged somehow and the browser can't run it. (Compression issue, maybe?). Should the swf be in the images directory or some other directory under assets? If it is a compression/decompression issue can the swf be exempted from this? 

If I take the swf out of the assets directory and put it in the web-app directory and use an embed tag like
```
<embed src="swf/myapp.swf" ...etc.>
```

It works.

Regards,
Rob

**Comment by davydotcom** [comment]
Weird, we arent doing any special processing with swf files. Simply returning the raw byte stream. Is it possible the content-type is not properly being evaluated by the asset-pipeline for this file format?

**Comment by robbugh** [comment]
Maybe. Does the plugin compress the swf file? It appears the file is 
streamed back to Firefox but it is damaged somehow.

Rob

**Comment by davydotcom** [comment]
it does not. if the browser accepts gZIP it will return a gz version of the file but thats normal browser compression/decompression
--
David Estes

On February 18, 2015 at 9:59:22 AM, Rob Bugh (notifications@github.com) wrote:

Maybe. Does the plugin compress the swf file? It appears the file is
streamed back to Firefox but it is damaged somehow.

Rob

**Comment by davydotcom** [comment]
how big is the swf file. im trying to reproduce with little luck

**Comment by davydotcom** [comment]
Cant reproduce tried both grails 2.4 and grails 3
