### ISSUE TITLE
Documentation link points to the ApiDocs instead of UserGuide

### ISSUE THREAD

**Issue by aadrian** [bertramdev/asset-pipeline#225]
The Documentation link from the plug-in page: http://plugins.grails.org/plugin/grails/asset-pipeline
points the JavaDocs: https://bertramdev.github.io/asset-pipeline/  instead of the UserGuide http://www.asset-pipeline.com/manual/  (this is what the users are really interested in :) ).

Thank you.

**Comment by davydotcom** [comment]
fiixng in 3.2.3
