### ISSUE TITLE
How to deactivate one asset pipeline plugin for some files.

### ISSUE THREAD

**Issue by asteria277** [bertramdev/asset-pipeline#227]
Hi,

I would like to deactivate an asset pipeline plugins for some files.

For example, I use the plugin 'angular-annotate-asset-pipeline'. For the moment, this plugin is executed on all the javascript files but it would save time to not run ng-annotate.js on file like 'jquery', 'bootstrap', ...

Is there a way to achieve this with the current asset pipeline plugin ?

**Comment by davydotcom** [comment]
Essentially you want to skip this processor for everything but a few. This would be a feature request for @craigburke . There are a couple ways this could be done. One example might be to have the processor look for an annotation at the top of the file stream before running it through the annotation runtime in rhino.

**Comment by asteria277** [comment]
Hi @davydotcom . Thanks for your reply.
But would it not be better to handle this in asset-pipeline itself rather than implementing something in all sub plugins where this is needed ? I agree that for now I only need this for annotate-asset, but in the future it might be needed for another one.

**Comment by davydotcom** [comment]
The trick is determining is this a white list or black list scenario.

i.e. you could make a directive for it like:

```
//= skip_processor AnnotateProcessor
//or
//= use_processor AnnotateProcessor
```

The downside to this however is you have to determine if the plugin runs in white list or black list mode, Also you have to add this directive to every single file you want this to be a factor on.

**Comment by asteria277** [comment]
In my case I think that a while list would be better. I prefer to add a directive in a file I own rather having to change files like jquery, ckeditor or bootstrap.
But of course this would mean that plugin is not backward compatible, unless we add a configuration setting to choose to activate the while list or not ...

Or wouldn't be better to add a new setting like :

grails.assets.processor.AnnotateProcessor.includes = "angular/**" 
grails.assets.processor.AnnotateProcessor.excludes = "bootstrap/**"
