### ISSUE TITLE
Excluded file could not be found in production 

### ISSUE THREAD

**Issue by confile** [bertramdev/asset-pipeline#229]
I tried to exclude pdf files from being processed with: 

```
grails.assets.excludes = ["**/*.pdf"]
```

In my GSP I do: 

```
<a href="${assetPath(src: 'someName.pdf', absolute:true)}" target="_blank">Download PDF</a> 
```

It works well in dev mode but in production the file could not be found.

**Comment by davydotcom** [comment]
You excluded the file so it would never be copied into your final war file.
--
David Estes

On February 25, 2015 at 9:04:51 PM, Confile (notifications@github.com) wrote:

I tried to exclude pdf files from being processed with:

grails.assets.excludes = ["**/*.pdf"]

In my GSP I do:

<a href="${assetPath(src: 'someName.pdf', absolute:true)}" target="_blank">Download PDF</a>  

It works well in dev mode but in production the file could not be found.

**Comment by confile** [comment]
How can I access an excluded file like in my case?

**Comment by davydotcom** [comment]
You cant you excluded it. Thats the entire point of exclude. Not sure why you are excluding a pdf file exactly considering its considered a GenericAsset. the effect of processing a file with a pdf extension is simply copying it into your war file , digest naming it and gzipping it. Nothing special
--
David Estes

On February 26, 2015 at 8:50:29 AM, Confile (notifications@github.com) wrote:

How can I access an excluded file like in my case?

**Comment by confile** [comment]
I want to exculde it because in production the name of the file changes from ``someName.pdf`` to someName-234823492349.pdf``.  How can I keep the original name?

**Comment by davydotcom** [comment]
If you do not want to use digest names for expiring the answer is to simply place the pdf file in the web-app folder instead of assets folder.
--
David Estes

On February 26, 2015 at 9:07:48 AM, Confile (notifications@github.com) wrote:

I want to exculde it because in production the name of the file changes from someName.pdf to someName-234823492349.pdf``. How can I keep the original name?

**Comment by confile** [comment]
You are wright thank you!

**Comment by confile** [comment]
And how do I access the files in the web-app folder?
