### ISSUE TITLE
Allow runtime control of base URL

### ISSUE THREAD

**Issue by caleeky** [bertramdev/asset-pipeline#230]
I have a bit of an unusual use-case that drives this request.

I have a Grails application which is used to generate web based reports, of a fashion. These reports are normally used by internal corporate users. Occasionally, however, these reports need to be published to an externally facing server. 

By publish, I mean that the HTML generated by the Grails application needs to be uploaded to that external server, where they will be served. This external server also hosts the content of the assets/ folder of the built WAR. Of course, versioning of published assets, for compatibility, is controlled. However, the assets are served from a different base URL than they are from the original Grails deployment.

E.g. assets would be served from the Grails deployment from /app/assets/... while the assets on the external server are served from /pubassets/app/v1/...

The workaround I apply today is to have a publish tool automatically replace embedded URLs. I would rather have the asset pipeline generate the correct URLs directly, but only when certain parameters are passed at runtime.

**Comment by JohnTheBeloved** [comment]
Please, I have a similar issue too

see https://github.com/bertramdev/asset-pipeline/issues/231 and http://stackoverflow.com/questions/28880261/resolving-asset-links-to-assets-using-their-absolute-url

**Comment by davydotcom** [comment]
assetPath taglib does this with absolute:true

**Comment by caleeky** [comment]
davydotcom's response was related to JohnTheBeloved's question, but not mine. That said, I discovered that my requirement could be satisfied using the config setting:

environments {
	development {
		grails.assets.url = grails.assets.url = { request ->
			// Logic goes here - set attributes on request to direct this logic
		}
	}
}
