### ISSUE TITLE
Resolving <asset/> links to assets using their absolute URL

### ISSUE THREAD

**Issue by JohnTheBeloved** [bertramdev/asset-pipeline#231]
In a grails application, I want to use the absolute url to resolve an asset in a grails application, but unlike the absolute attribute for * and , the asset pipeline does not have a way to resolve assets using an absolute link resolved by grails.serverURL.

Anyone can tell me of an alternative with is not by using the resources plugin?

Stackoverflow question here

http://stackoverflow.com/questions/28880261/resolving-asset-links-to-assets-using-their-absolute-url

**Comment by davydotcom** [comment]
not sure if you looked at grails.assets.url spec

**Comment by davydotcom** [comment]
you can configure the grails.assets.url to a specific url for absolute paths. It even passes the request object if you want to use that to determine the base url. this can be a string or closure where the closure gets run every time an asset is requested.

**Comment by JohnTheBeloved** [comment]
Thanks, seen it
