### ISSUE TITLE
Grails3 assets folder structure

### ISSUE THREAD

**Issue by benorama** [bertramdev/asset-pipeline#233]
I'm currently trying to migrate some apps/plugins to grails3 and encounter some issue with assets pipeline.

My current assets folder structure is:
- dependencies/libs (new folder for all bower dependencies, which usually includes a mix of js/css files)
- images (default)
- javascripts (default)
- stylesheets (default)

In Grails2, we were able to reference js/css files outside of javascript/stylesheets folder.
In Grails3, it looks like it's not possible.

For example in my app main css file `grails-app/assets/stylesheets/application.css`, I put:

```css
/*
*= require libs/bootstrap/dist/css/bootstrap
*/
```

If I put the bootstrap files in `grails-app/assets/dependencies/libs/bootstrap/dist/css/`, it does not work anymore.
I have to put it in `grails-app/assets/stylesheets/libs/bootstrap/dist/css/` to make it work.

Is it a new requirement? (all css files in stylesheets folder / js files in javascripts folder)

Thanks.

**Comment by davydotcom** [comment]
not it should be able to go into your libs folder. ill check the code and see what sup
--
David Estes

On March 6, 2015 at 3:48:45 PM, Benoit Hediard (notifications@github.com) wrote:

I'm currently trying to migrate some apps/plugins to grails3 and encounter some issue with assets pipeline.

My current assets folder structure is:

dependencies/libs (new folder for all bower dependencies, which usually includes a mix of js/css files)
images (default)
javascripts (default)
stylesheets (default)
In Grails2, we were able to reference js/css files outside of javascript/stylesheets folder.
In Grails3, it looks like it's not possible.

For example in my app main css file grails-app/assets/stylesheets/application.css, I put:

/*
*= require libs/bootstrap/dist/css/bootstrap
*/
If I put the bootstrap files in grails-app/assets/dependencies/libs/bootstrap/dist/css/, it does not work anymore.
I have to put it in grails-app/assets/stylesheets/libs/bootstrap/dist/css/ to make it work.

Is it a new requirement? (all css files in stylesheets folder / js files in javascripts folder)

Thanks.

**Comment by davydotcom** [comment]
Ok figured it out. It appears the grails3 asset-pipeline plugin is grabbing an old core version. Add this to your buildscript dependencies and project dependencies:

`com.bertramlabs.plugins:asset-pipeline-core:2.1.1`

**Comment by benorama** [comment]
OK, thanks!
