### ISSUE TITLE
I can´t access to all files in assets directory from a jar file Using Extjs 4.2.1 and Grails 2.3.7

### ISSUE THREAD

**Issue by antonyperez** [bertramdev/asset-pipeline#234]
Hi
I have a problem with my application, I have a core-app as a main project and I am creating plugins to integrate more models for it, also I am using Extjs for front-end, every plugin contains domain classes, controllers, services, views and assets, all of this is deploy to a local maven repository,
Plugin-xx
grails-app
---controllers
---domain
---services
---views
---assets
------javascripts
---------plugin
------------controller
------------locale
------------model
------------store
------------view

When we use grails.plugin.location.' plugin-xx ' = "../plugin-xx " in the BuildConfig.groovy to add a plugin to the core-app all works fine, but when I packaged a plugin as a jar file with binary mode ( grails maven-deploy "--repository=XX" –binary) and we used it in the core-app and execute “grails run-app” the core-app can´t access to the jar assets/locale files, we checked the jar file and those files are in /META-INF/assets/plugin/locale/plugin-lang-classes.js.

The odd thing is that all Extjs code in the controller, model, store and view folders of the jar works fine.

Another thing is that when I execute “grails run-war” my jar
/META-INF/assets/plugin/
controller
locale
model
store
view
folders are not found.

I am using

    JDK1.7, Grails 2.3.7, asset-pipeline 2.1.4, Extjs 4.2.1

**Comment by davydotcom** [comment]
Fixed in 2.2.1
