### ISSUE TITLE
recognize bower dependencies

### ISSUE THREAD

**Issue by hansgru** [bertramdev/asset-pipeline#235]
the asset pipeline plug-in should recognize Bower assets in that directory and not mess everything up. To force the user to specify everything would mean to duplicate the effort Bower is already doing.

**Comment by davydotcom** [comment]
can you clarify? People use bower with AP all the time and recognize assets?

**Comment by hansgru** [comment]
> can you clarify? People use bower with AP all the time and recognize assets?

How do they use it? I found no clean explanation.
I red some blog posts that suggest simply putting them
in ```/grails-app/assets/bower_components```, and than just including them with
```
//= mylib/mylib.js
```
in the files that will be included with the ```<asset:..``` tag but that will produce quite allot of "garbage" in ```target/assets``` when I run ```asset-precompile```

**Comment by davydotcom** [comment]
you can use exclude patterns to control that if you wish. typically you would require a file from bower into your application.js file. But you don't want to exclude everything from bower either. It has image assets and fonts sometimes you want to grab too. A convenient mod might be to be able to read the bower.json file and use that to assist in determining what to include/exclude. Assuming this file is consistent of course.

**Comment by hansgru** [comment]
>  A convenient mod might be to be able to read the bower.json file and use that to assist in determining what to include/exclude.

Exactly this is what I expected the AssetPipeline plug-in to do if it had any Bower support :).

Also when I include a dependency like: ``` //=require myLib/mylib.js``` to recognize if there's a ```myLib/bower.json``` and if it has dependencies, to include those too if they are not already added.

**Comment by davydotcom** [comment]
Well PR’s are of course most welcome .
--
David Estes

On March 17, 2015 at 9:43:56 AM, Hans (notifications@github.com) wrote:

A convenient mod might be to be able to read the bower.json file and use that to assist in determining what to include/exclude.

Exactly this is what I expected the AssetPipeline plug-in to do if it had any Bower support :).

Also when I include a dependency like: //=require myLib/mylib.js to recognize if there's a myLib/bower.json and if it has dependencies, to include those too if they are not already added.

**Comment by davydotcom** [comment]
closing this one due to other raised issues. will look into how we do this in an extensible manor. Not going to make it embedded into the  core plugin
