### ISSUE TITLE
Where to put 'grails.assets.minifyJs' and similar settings?

### ISSUE THREAD

**Issue by hansgru** [bertramdev/asset-pipeline#236]
Where to put 'grails.assets.minifyJs' and similar settings? in BuildConfi.groovy? in Config.groovy?

The documentation mentions nothing.

**Comment by davydotcom** [comment]
Config.groovy
--
David Estes

On March 17, 2015 at 9:25:57 AM, Hans (notifications@github.com) wrote:

Where to put 'grails.assets.minifyJs' and similar settings? in BuildConfi.groovy? in Config.groovy?

The documentation mentions nothing.

**Comment by hansgru** [comment]
Thank you.
