### ISSUE TITLE
master and tags outdated 3.0.5 vs. 3.0.7

### ISSUE THREAD

**Issue by flxtr** [bertramdev/asset-pipeline#237]
In the wild, asset-pipeline 3.0.7 is available (https://plugins.grails.org/plugin/bertramlabs/asset-pipeline-grails ), but master branch and newest tag here is version 3.0.5.

Am I getting something wrong or did you forget to push something?

Thx

flxtr

**Comment by davydotcom** [comment]
old story, bug in plugins portal. looks to be fixed
