### ISSUE TITLE
Exclude bower excluded resources by default.

### ISSUE THREAD

**Issue by hansgru** [bertramdev/asset-pipeline#237]
Since many projects use Bower for web resource management and dependency, please add support to automatically exclude the resources Bower is already excluding.

Under ``` assets/bower_components``` each library (and it's dependencies) has a ```bower.json``` with a ```ignore``` section that could be directly used.

See #235 discussion.

**Comment by davydotcom** [comment]
Cant rely on the specification of bower as its inconsistent.
