### ISSUE TITLE
plugin assets give 404 - Grails

### ISSUE THREAD

**Issue by snimavat** [bertramdev/asset-pipeline#239]
Asset pipeline 3.0.8

There are two issues

1. The css asset which is present in plugin jar at meta-inf/assets gives 404 - the path to asset is correct but the ClassPathResource is not being found
2. Coffee assets are included in plugin jar as it is without being compiled.

It would be great to have some docs about how assets are packaged in plugin jars.
Where they are kept, how they are resolved. and if the coffee/less are supposed to be compiled and then included in jar or should be included as it is. that will help developers investigate issue.

**Comment by davydotcom** [comment]
Spoke on slack. this is related to a grails plugin not being set to pluginPackage=true in gradle. This leaves an `assets/manifest.properties` file on the classpath that makes asset-pipeline think it has all the assets it needs.
