### ISSUE TITLE
Is there a 'grails.assets.minifyCss' setting ?

### ISSUE THREAD

**Issue by hansgru** [bertramdev/asset-pipeline#239]
Is there a 'grails.assets.minifyCss' setting? To be able to set it to false ? in order to be able to easier find out what when wrong or if the parts will get merged correctly?

**Comment by davydotcom** [comment]
yes its called exactly that
--
David Estes

On March 17, 2015 at 10:06:53 AM, Hans (notifications@github.com) wrote:

Is there a 'grails.assets.minifyCss' setting? To be able to set it to false ? in order to be able to easier find out what when wrong or if the parts will get merged correctly?

**Comment by hansgru** [comment]
thank you.
