### ISSUE TITLE
 Would not work for grails 2.2.4? - Error Failed to resolve dependencies

### ISSUE THREAD

**Issue by madasaca29** [bertramdev/asset-pipeline#240]
Try installing it in grails 2.2.4 and generates this error:

Error Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):
- org.grails.plugins:asset-pipeline:2.1.5

any ideas?

**Comment by davydotcom** [comment]
We just released 2.2.0 see if that works for ya
