### ISSUE TITLE
Update Ratpack classes to ratpack.service.Service 

### ISSUE THREAD

**Issue by johnrengelman** [bertramdev/asset-pipeline#242]
https://github.com/bertramdev/asset-pipeline/blob/master/ratpack-asset-pipeline/src/main/java/asset/pipeline/ratpack/AssetPipelineService.java uses a deprecated class. This should be replaced with the corresponding classes in `ratpack.service`

**Comment by davydotcom** [comment]
Thanks will check it out

**Comment by johnrengelman** [comment]
Fixes here: https://github.com/bertramdev/asset-pipeline/pull/243
