### ISSUE TITLE
Encoding of JS files for CKEditor for UTF-8 with BOM

### ISSUE THREAD

**Issue by osugregor** [bertramdev/asset-pipeline#243]
After upgrading from 1.8.3 to 2.1.5 I started to have problems serving JS files for CK Editor.

I think I have pinned it down to the CK Editor files having BOM bytes.

Curious if BOM should be supported, or if I should manually convert all the CK Editor files to UTF-8 w/o BOM.

Thanks,
Greg

**Comment by davydotcom** [comment]
Maybe attempt using custom encoding not sure here. http://bertramdev.github.io/asset-pipeline/guide/usage.html#encoding

**Comment by davydotcom** [comment]
If we can get a sample project I can take a look and see whatsup
