### ISSUE TITLE
Assets not working in standalone WAR/JAR in Grails 3

### ISSUE THREAD

**Issue by hojerst** [bertramdev/asset-pipeline#244]
running a standalone jar or war that is build with grails 3 will not work as expected:

jar (precompiled true or false): generates without digest (uncachable); assets are accessible
war (precompiled true): generates urls with digest; assets are empty
war (precompiled false): generates urls without digest (uncachable); assets are empty

example:
java -Dgrails.env=prod -jar build/libs/myapp.war

**Comment by davydotcom** [comment]
what version?

**Comment by davydotcom** [comment]
Aha, looks like something was broken in RC3 and up. 2 PR's related to this have been submitted to grails-core as well as a new version of AP grails has been staged for the grails 3.0.1 release

**Comment by hojerst** [comment]
Just for documentation:
WEB-INF/lib/asset-pipeline-core-2.1.1.jar
WEB-INF/lib/asset-pipeline-3.0.0.jar
