### ISSUE TITLE
Borking on building war file

### ISSUE THREAD

**Issue by andyrh3** [bertramdev/asset-pipeline#246]
When trying to build prod war I get the following error. I have even tried to delete all of the js content and still it's complaining about a character issue. 

Not happy - thinking of just using Grunt.

|Precompiling Assets!
|Processing File 1 of 5 - favicon.ico
|Processing File 2 of 5 - application.js
|Uglifying File 2 of 5 - applicationApr 04, 2015 2:33:29 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: application.unminified.js:1: ERROR - Parse error. Character '»' (U+00BB) is not a valid identifier start char
ï»¿(function ($, window, document, undefined) {
 ^

Apr 04, 2015 2:33:29 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 1 error(s), 0 warning(s)

|Compressing File 2 of 5 - application
|Processing File 3 of 5 - utilities.js
|Uglifying File 3 of 5 - utilitiesApr 04, 2015 2:33:30 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: utilities.unminified.js:1: ERROR - Parse error. Character '»' (U+00BB) is not a valid identifier start char
ï»¿(function ($, window, document, undefined) {
 ^

Apr 04, 2015 2:33:30 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 1 error(s), 0 warning(s)

**Comment by davydotcom** [comment]
Looks like Closure Compiler is having issues with a special character. you can turn off minification if you want. Or figure out why your js file has a bad character in it. Its telling you that a file you are including has a junk character.
--
David Estes

On April 4, 2015 at 9:40:46 AM, andyrh3 (notifications@github.com) wrote:

When trying to build prod war I get the following error. I have even tried to delete all of the js content and still it's complaining about a character issue.

Not happy - thinking of just using Grunt.

|Precompiling Assets!
|Processing File 1 of 5 - favicon.ico
|Processing File 2 of 5 - application.js
|Uglifying File 2 of 5 - applicationApr 04, 2015 2:33:29 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: application.unminified.js:1: ERROR - Parse error. Character '»' (U+00BB) is not a valid identifier start char
ï»¿(function ($, window, document, undefined) {
^

Apr 04, 2015 2:33:29 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 1 error(s), 0 warning(s)

|Compressing File 2 of 5 - application
|Processing File 3 of 5 - utilities.js
|Uglifying File 3 of 5 - utilitiesApr 04, 2015 2:33:30 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: utilities.unminified.js:1: ERROR - Parse error. Character '»' (U+00BB) is not a valid identifier start char
ï»¿(function ($, window, document, undefined) {
^

Apr 04, 2015 2:33:30 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 1 error(s), 0 warning(s)

**Comment by phidias51** [comment]
I wonder if the character encoding on the stream is not set properly.
Should be utf-8.

**Comment by davydotcom** [comment]
Default is UTF-8 you can even ensure character encoding on the stream by adding a //=encoding UTF-8 directive

This is documented here: http://bertramdev.github.io/asset-pipeline/guide/usage.html#encoding
--
David Estes

On April 4, 2015 at 10:22:18 AM, Mark Fortner (notifications@github.com) wrote:

I wonder if the character encoding on the stream is not set properly.
Should be utf-8.

**Comment by davydotcom** [comment]
https://github.com/bertramdev/asset-pipeline-core/blob/master/asset-pipeline-core/src/main/groovy/asset/pipeline/AbstractAssetFile.groovy#L74 Shows how a stream is read off of a file. If encoding is not specified the java default encoding for your OS is picked up

**Comment by andyrh3** [comment]
No longer working on this project, but thank you all for your comments :-)
