### ISSUE TITLE
Assets to the S3 Bucket are uploaded with the hash code appended while on retrieving them no hash code is appended in the request

### ISSUE THREAD

**Issue by parasjain** [bertramdev/asset-pipeline#248]
I recently configured grails-cdn-asset-pipeline on my project. I happened to notice that the assets in my S3 bucket are uploaded with some random hash code appended to them. However while retrieving them the hash code are not being appended in the request as a result it shows "Failed to load resource: the server responded with a status of 403 (Forbidden)"
I referred to the issue section for this but found that the owner has close this issue with the following response "This behavior is not linked to this plugin but to the Asset Pipeline Plugin".

**Comment by davydotcom** [comment]
What taglib are you using to request the file

**Comment by parasjain** [comment]
It is working if I am running war file. But how can I use in in development mode.
I am using asset taglib for request.
Here is the code snippet for my gsp file:
 <asset:javascript src="site/site.js" /> 
<asset:javascript src="common/mordnizr.js" />
 <asset:stylesheet href="site/site.css" />

**Comment by parasjain** [comment]
Here is the code snippet for my gsp file:
 <asset:javascript src="site/site.js" /> 
<asset:javascript src="common/mordnizr.js" />
 <asset:stylesheet href="site/site.css" />

**Comment by davydotcom** [comment]
blank?

**Comment by davydotcom** [comment]
oh you do not reference digested assets in development mode that only is in production mode. for development mode to facilitate fast reloading the assets should be pointed at your local environment.
