### ISSUE TITLE
Documentation: Explain manifests

### ISSUE THREAD

**Issue by phidias51** [bertramdev/asset-pipeline#249]
Please add some explanatory text to the section in the documentation on manifests:

//This is a javascript file with its top level require directives
//= require jquery
//= require app/models.js
//= require_tree views
//= require_self
console.log("This is my javascript manifest");

Specifically:
- is the manifest only for managing javascript dependencies, or can it manage web component dependencies?  For example, if I have a web component located in assets/my-component with a mixture of css, js, and html files, will the manifest allow me to serve up those files?

- what does *require jquery* do? Does it fetch jquery from a CDN? Does it serve up jquery from assets/jquery, or assets/javascript/jquery?

- what does *require app/models.js* do?  Where is it expecting to find models.js? In assets/javascript/app or in asset/app?

- what does *require_tree views* do? Does that make everything in your grails-app views directory accessible?

**Comment by hansgru** [comment]
Actually some of them are explained here pretty detailed:
http://bertramdev.github.io/asset-pipeline/guide/usage.html#directives

More and better examples and docs are however always nice :).

**Comment by davydotcom** [comment]
Of course , also any contributions to the docs are most welcome it's a lot to cover. Thanks for the feedback
