### ISSUE TITLE
jquery processing error during war build 

### ISSUE THREAD

**Issue by patriot21** [bertramdev/asset-pipeline#250]
I have a project setup with bower (it writes the bower_components dir into grails-app/assests).  It runs properly using run-app but when I run-war I get an error.

>| Processing File 285 of 1129 - jquery/src/intro.js  
>| WAR packaging error: [error: couldn't process source due to parse error, Unexpected token (45:0)]

Since this is just a jquery file I am confused as to why this is a problem.  Its the latest 2.1.3 version of jquery pulled in by bower and I am using grails 2.4.4 with the 2.1.5 version of the pipeline.  Any ideas on how to fix this or what I am doing wrong?

I have also tried to have the asset pipeline ignore the file but I have no had any luck with this:

>grails.assets.excludes = ["bower_components/jquery/src/*.js"]

Which is the way to exclude a file.

**Comment by davydotcom** [comment]
at what tree level is bower_components?

**Comment by davydotcom** [comment]
it may just be grails.assets.excludes=["jquery/src/*.js"] but that token error implies there is some weird character in there we need to determine what that is

**Comment by patriot21** [comment]
Thanks David,  I will give that a try as the bower_components is just in assets.

Its seems the integration with bower could be better.  If you have thoughts on what a bower assests plugin might look like let me know.  I am happy to contribute it.

**Comment by davydotcom** [comment]
assuming this is a fixed issue atm, bower support soon to come
