### ISSUE TITLE
plugin doesn't process filenames starting with _

### ISSUE THREAD

**Issue by fedotxxl** [bertramdev/asset-pipeline#260]
<script src="/assets/angular/libs/angular.safeApply-08786da7be5cdc09b61b2521814d0b27.js" type="text/javascript" ></script>
        <script src="/assets/angular/common/_modal.js" type="text/javascript" ></script>

All files starting with `_` doesn't have hash at the end and server returns 404 for them

**Comment by davydotcom** [comment]
anything with an _ is default excluded from build. It is considered a partial and expected that you load them into your final bundle with a `//=require`

**Comment by davydotcom** [comment]
If you want to include these types of files individually, which is a bit inefficient you can do so by adding the following includes pattern to the config ` **/_*.*`
