### ISSUE TITLE
File was not sourced from the same ScanDirectory

### ISSUE THREAD

**Issue by VenelinPetkov** [bertramdev/asset-pipeline#263]
grails 3.0.2

ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet grailsDispatcherServlet threw exception
java.lang.RuntimeException: File was not sourced from the same ScanDirectory /..../grails-app/assets/components/react/react.js scanDir: /...../grails-app/assets/javascripts
	at asset.pipeline.fs.

**Comment by davydotcom** [comment]
Im not exactly sure what the issue is here. This means you are improperly requiring a file.
