### ISSUE TITLE
Incorrect sourceMappingURL

### ISSUE THREAD

**Issue by fedotxxl** [bertramdev/asset-pipeline#265]
I've got js file in directory `/assets/angular/views/event/updateDatesAndTemplates.js`. Asset-pipeline added following:

`//# sourceMappingURL=angular/views/event/updateDatesAndTemplates.js.map`

Since this is relative url Chrome tries to load file by `assets/angular/views/event/angular/views/event/updateDatesAndTemplates.js.map`

1. You have to make it absolute (is it correct?) or omit path
2. (optional) Specification requires //# sourceMappingURL at the end of the file (not beginning) - https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.zhn1phd7ocnp

**Comment by davydotcom** [comment]
What version of asset-pipeline and grails are you using?

**Comment by davydotcom** [comment]
Actually this was fixed in a PR recently

**Comment by davydotcom** [comment]
the grails3 plugin version that has the fix is tagged and pending release to bintray, should be out later today.

**Comment by fedotxxl** [comment]
we use grails 3

**Comment by davydotcom** [comment]
I meant which asset-pipeline version but I'm assuming your using the default version (i.e. latest) also helps to specify grails 3.0.1 or 3.0.2. Also the gradle asset-pipeline version is handy to know. 

But This issue was raised a while back and a release is pending with a fix. :)

**Comment by fedotxxl** [comment]
Grails 3.0.1, `classpath 'com.bertramlabs.plugins:asset-pipeline-gradle:2.2.3'` 

>But This issue was raised a while back and a release is pending with a fix. :)

got it

**Comment by davydotcom** [comment]
Fixed
