### ISSUE TITLE
How to remove var process = process || {env: {NODE_ENV:

### ISSUE THREAD

**Issue by aberbenni** [bertramdev/asset-pipeline#266]
Is there any way (eg. config option) to get rid of `var process = process || {env: {NODE_ENV:` string at the beginning of file?

**Comment by Janvanoorschot** [comment]
I have just asked a similar question in https://stackoverflow.com/questions/64632219/grails-run-app-services-javascript-starting-with-node-env-line.

**Comment by Janvanoorschot** [comment]
I have posted an answer in the above mentioned stackoverflow question. This answer might be of use to you.
