### ISSUE TITLE
asset-pipeline dose not work if i unzip the war file to tomcat with grails 3.0.3

### ISSUE THREAD

**Issue by beneo** [bertramdev/asset-pipeline#267]
1. I create a new grails app 
    > grails create-app App

2. I change the asset-pipeline-gradle version to 2.3.8 in build.groovy 
3. I deploy the application with command

    > grails dev war

4. I just run command

    > java -jar App.0.1.war

    and it works fun, the css js and images all work ok

5. and if i unzip the war file and copy all the files to my custom tomcat fold, the tomcat startup normally, but the css, js can not display
6. Can you help me, the speed me 2 days to reappear the issue, and i really do not know how to fix this issue

**Comment by beneo** [comment]
tomcat 8.0.24
jdk 1.8.45

**Comment by songday** [comment]
I encountered the same problem, trying the latest version: 2.4.3

**Comment by hansgru** [comment]
> what's the difference between asset-pipeline-3.0.5.jar and asset-pipeline-core-2.3.8.jar

3.x is for Grails 3.x and 2.x is for Grails 2.x ?

**Comment by songday** [comment]
> 3.x is for Grails 3.x and 2.x is for Grails 2.x ?
I guess they are different, they are all exist in lib directory

**Comment by songday** [comment]
Hi @hansgru , did you occur this issue?
unzip the war file (created by running grails war) to a directory, serve by Tomcat
all resource files won't be loaded

**Comment by hansgru** [comment]
@songday 
This is not how productive Tomcat deployment is supposed to happen:
1. Unzip tomcat from http://tomcat.apache.org somewhere on your system.
2. build the war file from grails with ```%> grails war```
3. copy the war file (from the built ```project/target```) to ```$tomcat/webapps/``` (tomcat will automatically expand it, so there's no need to unpack it)
4. start Tomcat again (hot deployment is not the best idea even with Tomcat 8)

With Grails 2.5.1, java 8 or 7 and tomcat 8 or 7 this seems to work without problems using the newly released ```asset-pipeline:2.4.3```

Grails 3.x seems to be still missing important plug-ins so we can't start to convert our applications to it.

**Comment by songday** [comment]
@hansgru Thanks for your reply

Actually, asset-pipeline works fine in Grails 3.0.2
but since Grails 3.0.3 (include 3.0.4), have this issue

When I ran Grails app locally with env=dev, resources worked fine (Javascript, CSS, images, etc.)
then I deployed to production (env=prod), every resources were gone
I found that the page on production, didn't contain 'script' tag, and CSS (link rel="stylesheet")

**Comment by davydotcom** [comment]
^ I think this was a bug that came up earlier with grails not resolving your layouts and nothing to do with the asset-pipeline. Can you confirm the gsp layout is being applied to your view?

**Comment by songday** [comment]
Thanks for your reply

I guess I need to open an issue for Grails 3.0.4

do you guys still sticking to Grails 2.5.x?

**Comment by hansgru** [comment]
> do you guys still sticking to Grails 2.5.x?

Yes, and I suppose this will be for a long time.

**Comment by davydotcom** [comment]
Just a heads up for grails 3.x the serving assets from expanded war issue has since been resolved in version `asset-pipeline:3.0.6`
