### ISSUE TITLE
Grails3: problems loading asset resources from plugin

### ISSUE THREAD

**Issue by lguerin** [bertramdev/asset-pipeline#271]
I'm trying to use asset-pipeline inside a plugin and then use this plugin as a dependency of my app.
I'm facing some problems when I try to execute the app : assets are not loaded correctly when I use gradle "run" task. Otherwise, if I start the app from the binary jar file, everything is OK.

**My configuration**
grails -version
| Grails Version: 3.0.3
| Groovy Version: 2.4.3
| JVM Version: 1.7.0_79

gradle version: 2.3
OS: Linux Ubuntu

asset-pipeline version: 2.3.8

**Here is my test case**
- Create a plugin
grails create-plugin plugin --profile=web-plugin
- Create a dummy JS file plugin.js and add lodash as nested dependency: 

```
//= require lodash/lodash.min

function alertFromPlugin() {
    console.log("uniqueID: " + _.uniqueId());
    alert("JS loaded from my plugin with nested asset");
}
```
- Build and install plugin into maven repository:
gradle install

- Create an application
grails create-app app
- Add plugin dependency
- Build 
gradle assemble

When I run the app from the generated jar file, everything is OK, the alert box is displayed:
java -jar build/libs/app-0.1.jar
chrome http://localhost:8080/

But if I run the app directly from IntelliJ or from the gradle "run" task, alert box is not displayed and assets are not loaded correctly (404):
gradle run

Sources of my test case are available here: https://www.dropbox.com/s/ujn7ey03af9c4y0/issue.tar.gz?dl=0

**Comment by davydotcom** [comment]
this should have since been fixed with asset-pipeline:3.0.8 for grails
