### ISSUE TITLE
Released plug-in versions do not match the tags and releases in GitHub

### ISSUE THREAD

**Issue by hansgru** [bertramdev/asset-pipeline#277]
The released plug-in version do not match the tags and releases on GitHub, i.e. there are published releases that have no tag/release on GitHub :(.

**Comment by davydotcom** [comment]
This should not be the case youll have to provide an example but i tend to tag most releases

**Comment by davydotcom** [comment]
Fixed missing `2.4.0` and `2.4.3` Tags. It should be noted some versions were skipped in `2.4.x` and `2.3.x` due to fixes in the `asset-pipeline-core` repository
