### ISSUE TITLE
Plugin resource excludes does not work for all plug-ins.

### ISSUE THREAD

**Issue by hansgru** [bertramdev/asset-pipeline#278]
The exclusion of plug-in resources as specified in the docs, does not seems to work for all plug-ins.

E.g. 
```Groovy
grails.assets.plugin."excel-export".excludes=["**/*"]
``` 
will work (those resources will be removed), but:
```Groovy
grails.assets.plugin.twitterbootstrap.excludes=["**/*"]
``` 
or even:
```Groovy
grails.assets.plugin."twitterbootstrap".excludes=["**/*"]
``` 
will **not work** at all :(.

In the case of Twitter Bootstrap plug-in we need the functionality, but not  it's resources since we have customized ones. This requirement is the most common one with TB.

This happens even with the very recent Grails 2.5.1, Java 8, asset-pipeline:2.4.3, and twitter-bootstrap:3.3.4

Thank you.

**Comment by davydotcom** [comment]
Note the name of the plugin is not `twitterbootstrap` but is actually `twitter-bootstrap`
