### ISSUE TITLE
The Grails Shell does not pick Config.groovy changes to the asset-pipeline config

### ISSUE THREAD

**Issue by hansgru** [bertramdev/asset-pipeline#279]
When changing the configuration in ```Config.groovy``` for the asset-pipeline plug-in  (e.g. tuning the excludes/includes), the changes are not picked by the grails shell. So even doing:
```bat
grails > clean
grails > compile
grails > war
```
Won't pick the changed config - e.g. new excludes. The ```target/assets``` will have everything regenerated with the **old** rules. 

One needs to exit the grails shell, and re-start it again for **every** single config change.
This is extremely counter productive, and undermines the role of the grails shell.
Using an IDE, this effect is even more visible.

Thank you.

**Comment by davydotcom** [comment]
Unfortunately this has nothing to do with the `asset-pipeline`.
