### ISSUE TITLE
Outputting URLs that end with .gz if .gz version of asset exists

### ISSUE THREAD

**Issue by rgoldberg** [bertramdev/asset-pipeline#280]
Some hosting services, such as CloudFront with an S3 origin, cannot conditionally serve a pre-compressed .gz version of a file instead of the normal non-gzipped version based on the presence of the HTTP header `Accept-Encoding: gzip`.

Instead, the client must explicitly use one URL for the non-gzipped version, and a different URL for the gzipped version.  e.g., `http://hostname.com/path/to/asset.js` & `http://hostname.com/path/to/asset.js.gz`, respectively.

It would be useful for Asset Pipeline to have a setting, possibly named `grails.assets.useGzUrls`, that will, when set to `true`, cause Asset Pipeline to append `.gz` to the URL that it generates for an asset at runtime, if the request include the `Accept-Encoding: gzip` header, and if a .gz version of the asset "exists".

`useGzUrls` will not affect URLs that are rewritten in assets at asset precompile time, since the HTTP headers cannot be known at precompile time.

`useGzUrls` will default to `false`, which mimics the current behavior of Asset Pipeline.

.gz version existence could be determined differently in different contexts.  I don't know enough about `grails.assets.precompiled`, or some other settings, but I assume that the following algorithm could work:

1. if `grails.assets.url` is not set, or if it's null, or if it's a Closure that returns null, or if the value (or the value returned by the Closure) is a URL that does not include a host name (e.g., `/assets-path/`, `https:/path/to/asset/directory/`), then the Grails server will serve the asset, so, in this case, if the corresponding `.gz` file exists on the file system for a requested asset, then the output URL will have `.gz` appended to it
2. Otherwise, the asset will be served by whatever server is specified by the `grails.assets.url`.  In this case, it would be good to, at asset compile time, add generated .gz file names to `manifest.properties` (if that won't cause any problems), or to a new file (possibly named `gz.manifest.properties`, or some other, better name), so that Asset Pipeline could know which assets have a corresponding `.gz` file.  From what I know, `manifest.properties` is normally only used if `precompiled == true`.  In this mode `useGzUrls` would only work if the assets were precompiled, because, otherwise, there would be no file listing which `.gz` files exist on the external host.  This could be handled in a few ways:
  1. require `precompiled == true` for `useGzUrls == true` to have any effect
  2. have `precompiled` & `useGzUrls` both operate independently
  3. have `useGzUrls == true` automatically set `precompiled = true`, unless `precompiled` is explicitly set to `false`
  4. have `useGzUrls == true` automatically set `precompiled = true`, but, if `precompiled` is explicitly set to `false`, throw an exception

I prefer option ii, since it's the simplest.

If you don't have time to add it soon, I might try to implement this myself.

**Comment by rgoldberg** [comment]
Actually, you can probably ignore this, since if I use some origin for CloudFront other than S3, it can serve gzipped versions & non-gzipped versions from the same exact URL, switching between them based on the presence of the `Accept-Encoding: gzip` header.

So the need to use different URLs goes away.

**Comment by davydotcom** [comment]
correct this is not an issue at all with asset-pipeline this is an issue of a bad CDN capability
