### ISSUE TITLE
asset:stylesheet/asset:javascript generates incorrect URLs when src/href set as absolute

### ISSUE THREAD

**Issue by fedotxxl** [bertramdev/asset-pipeline#286]
Hello
If src (`asset:javascript`) or href (`asset:stylesheet`) starts with `/` (absolute path) than these methods generates incorrect urls:

`/assets//am.moviesList.js` - double `/` + missed hash in file name. 

Removing leading `/` fixes this problem. 
Asset pipeline version: 2.5.1

**Comment by rgoldberg** [comment]
Is this a recent change in behavior, or has it always been this way?

**Comment by davydotcom** [comment]
this may have been around a while actually

**Comment by davydotcom** [comment]
oh wait the / yea thats new it used to be aware of that

**Comment by rgoldberg** [comment]
I'll look through my changes and fix anything that might have caused this.

**Comment by rgoldberg** [comment]
When I looked at the AP code prior to my changes, it doesn't look like absolute paths would have worked, but maybe I misread something.

I've fixed this in my proprietary version of AP, but it's in a branch with some other changes.

I'll make a pull request later to integrate it into AP.

**Comment by davydotcom** [comment]
Entirely possible I broke it when we went to 2.x thanks I'll merge that one fast. Btw there is now a feature to not skip non digests I did get that merged in which may help your target cdn sync

**Comment by rgoldberg** [comment]
This fix is also in my fork, but buried in my branch.  Should I make a pull request as mentioned in my recent comment for #287?
