### ISSUE TITLE
Is there any way to have Asset Pipeline rewrite URLs for <g:javascript> tags in GSPs in plugins?

### ISSUE THREAD

**Issue by rgoldberg** [bertramdev/asset-pipeline#287]
Is there any way to have Asset Pipeline rewrite URLs for `<g:javascript>` tags in GSPs in plugins?

I want to use the value of `grails.assets.url` as the base URL for `src` attribute of the `<script>` element that `<g:javascript>` outputs.

I looked into setting `grails.resources.mappers.baseurl.default` to the same value as `grails.assets.url`, but I'm having problems getting that to work, so maybe you've already coded something like this.

If Asset Pipeline doesn't do this already, I have an idea about how to possibly code it myself using a `org.springframework.web.servlet.support.RequestDataValueProcessor`, which I can share if useful for others.

**Comment by davydotcom** [comment]
why not use `asset:javascript` instead

**Comment by rgoldberg** [comment]
Because I'm using a third-party plugin that has `<g:javascript>` tags.  These tags aren't in my own code.

I've actually fixed this issue in my forks of APC & AP.

I have a lot of changes in one branch.

It would save me a lot of time to just make a pull request for all the changes in that branch, and to then later refactor / factor out anything that you want modified / don't want.

Also, some of my changes should probably have config settings to enable / disable them, etc., so we could add those.

Should I create pull requests for my APC & AP forks so that you can easily compare all my changes to `master`?

**Comment by rgoldberg** [comment]
Created AP pull request #300 & APC pull request bertramdev/asset-pipeline-core#44 for these changes
