### ISSUE TITLE
sass-asset pipeline not working with gails 5

### ISSUE THREAD

**Issue by tobiaskraft** [bertramdev/asset-pipeline#288]
It seems that it is not possible to use the sass-asset pipeline with grails 5. When integrating the plugin and trying to compile a simple scss file the gradle process is disappearing unexpectedly. 
It seems that the problem is caused by compatibility problems with libsass and the newer gradle version that is used in grails 5. In grails 4 it is running without difficulties.

I have created a simple grails 5 project which is demonstrating the problem: https://github.com/tobiaskraft/test-pipeline

Compiling assets: 

`./gradlew clean assetCompile --stacktrace`

The following error is occurring:

```
    * Exception is:
    org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
    at org.gradle.launcher.daemon.client.DaemonClient.handleDaemonDisappearance(DaemonClient.java:252)
    at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:225)
    at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:187)
    ......

```

**Comment by longwa** [comment]
We are also having this same issue with one of our projects and Grails 5, the gradle daemon just dies with little fanfare.

**Comment by longwa** [comment]
FYI, I have confirmed this is not an issue with the upcoming sass-dart-pipeline changes.

**Comment by tobiaskraft** [comment]
Problem is fixed when using  the new sass-dart-pipeline.
