### ISSUE TITLE
Storage Path not working as documented

### ISSUE THREAD

**Issue by ctoestreich** [bertramdev/asset-pipeline#293]
I have set the storagePath to a directory per the documentation, but when hitting the bootstrap of the asset pipeline the AssetPipelineConfigHolder.manifest is null and does not use the storage path directory.  There is no additional information on specifying external manifests and we have the standard application.js and application.css manifests in our application.

<img width="1016" alt="screen shot 2015-09-10 at 9 57 38 am" src="https://cloud.githubusercontent.com/assets/691357/9791856/d30fa3ca-57a2-11e5-89c9-f5557c323840.png">

**Comment by ctoestreich** [comment]
While not ideal, the following fixes this.  I could not load up the manifest in my bootstrap as it was firing too late.

Should this be getting wired somewhere else?

<img width="1134" alt="screen shot 2015-09-10 at 10 42 23 am" src="https://cloud.githubusercontent.com/assets/691357/9792981/b711795e-57a8-11e5-8c0e-c198128d574e.png">

**Comment by davydotcom** [comment]
This is only designed to run in a run-war or war mode never in development mode.

**Comment by ctoestreich** [comment]
Yes, this was giving me null on the manifest in run-war.  I just did a run-war in debug and broke on the plugins bootstrap.

**Comment by ctoestreich** [comment]
And in other news... it is working now.  I had copied your script over with the change to the manifest retrieval.  Cleaning environment and making sure it isn't my changes.
