### ISSUE TITLE
assetResourceLocator.findAssetForURI is returning null in production

### ISSUE THREAD

**Issue by nburk2** [bertramdev/asset-pipeline#294]
Only in production and with any asset-pipeline version greater than 2.2.2 my call to assetResourceLocator.findAssetForURI("defaultIcons/thumbnail/bad.jpg") is returning null but when I call asset.assetPath(src: 'defaultIcons/thumbnail/bad.jpg') It says that it exists and it does when I go to it in a browser. 
    Any ideas as to why this would start happening after asset-pipeline version 2.2.2?

**Comment by davydotcom** [comment]
fixing in 2.5.5 release
