### ISSUE TITLE
Javascript library referencing an asset in production mode fails.

### ISSUE THREAD

**Issue by johancm** [bertramdev/asset-pipeline#297]
I created a test app to show the issue: https://github.com/johancm/atest

Run the application in development mode using: **gradle bootRun**
Everything works as expected.

Build a production jar using: **gradle build**
Run the jar using the **run.sh** script from the repository, and the modes and theme are not loaded.
The URL used to reference these assets are relative to the controller and not the application root.

**Comment by davydotcom** [comment]
this is not an ap bug. the path cannot be calculated for ace editor .you need to specify the path like you do with tiny mce init

**Comment by johancm** [comment]
Thanks David, setting the the path did the trick.

For Ace I did the following :
ace.config.set("basePath", "/assets/ace");

Might be useful to someone else.

Johan Marais |  Software Engineer | Owner
*∞*   http://gsltechnology.com.au <https://gsltechnology.com.au>
*=*   +61 44860 4290
*∝*   johan@gsltechnology.com.au
