### ISSUE TITLE
Accidental file commits increased .git from 9MB to 53MB

### ISSUE THREAD

**Issue by rgoldberg** [bertramdev/asset-pipeline#299]
Accidental file commits in changeset `1c5da512110b2c77ceeafb0caed5345ecbe52adf` increased `.git` from 9MB to 53MB.

You removed the files from the working directory in commit changeset `246e721b7ca2d37ec8348ea96c53a99710e0e089`, but `/git` is still six times its previous size.

Can you do something to remove those changesets, and replace the first one with a changeset that only includes the intended changes, not the excess files that swelled `.git`?

**Comment by davydotcom** [comment]
hmm any idea how to do this without breaking the public tree?

**Comment by rgoldberg** [comment]
I'm not expert at git (I normally use hg).  I can investigate.

Any reason why you closed this?

Did you find out that it's impossible to do without breaking the public tree?

Even if we have to break it, I think it might be worth it.  How many people do you think have cloned / fetched the repo since the commit?  Probably not too many.  And the released .zip files aren't impacted by this at all; only clones of the repo are impacted.
