### ISSUE TITLE
grailsw & grailsw.bat are Grails 2.2.4; application.properties is Grails 2.4.4

### ISSUE THREAD

**Issue by rgoldberg** [bertramdev/asset-pipeline#302]
`grailsw` & `grailsw.bat` are Grails 2.2.4; `application.properties` is Grails 2.4.4.

They should probably be the same version.

Any reason to not upgrade to the latest Grails 2.x, which is currently 2.5.1?

**Comment by davydotcom** [comment]
no reason just hasn't been done yet

**Comment by davydotcom** [comment]
upgraded wrapper to `2.5.1`
