### ISSUE TITLE
Asset Pipeline requires log4j?

### ISSUE THREAD

**Issue by olavgg** [bertramdev/asset-pipeline#315]
When I try to run a Spring Boot project with Asset Pipeline I get the following error
```
java.lang.IllegalStateException: Unable to load cache item
	....
Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at asset.pipeline.springboot.AssetPipelineService.<clinit>(AssetPipelineService.groovy)
```

It seems like log4j is required, but my project is configured with logback. If I add Log4j 1.x dependency it works fine,

**Comment by mkobel** [comment]
I usually add `log4j-over-slf4j` as dependency to resolve this issue:

e.g. `implementation 'org.slf4j:log4j-over-slf4j:2.0.4'`

**Comment by davydotcom** [comment]
4.5.1 switched to slf4j in all spots
