### ISSUE TITLE
Avoid processing files even if they are specified in a "//= require" statement

### ISSUE THREAD

**Issue by gsartori** [bertramdev/asset-pipeline#336]
Some `.js` files are not compatible with the processing from the Closure Compiler and they throw exceptions.

We can exclude them, but if they are part of a `//= require` the exclusion does not work.

We would like to use already minified .js files in a `//= require` without them to be processed from the Closure Compiler.

**Comment by davydotcom** [comment]
this is not how this works. we updated closure for next release. also can just set minifyJs=false if you dont want this

**Comment by gsartori** [comment]
It there a way we can include already minified JS (eg. libraries we don't need/want to debug) in a //= require_tree? We would like to keep a single file as an end result instead of linking different files.
