### ISSUE TITLE
CSS processor fails on certain values of url

### ISSUE THREAD

**Issue by gregopet** [bertramdev/asset-pipeline#35]
The CSS file for the Leaflet library contains a peculiar piece of CSS that throws `java.lang.StackOverflowError (no error message)` while processing the assets.

I've narrowed the problem down to this single line of CSS: `behavior: url(#default#VML);`

It's a [Microsoft proprietary extension](https://msdn.microsoft.com/en-us/library/ms530723(v=vs.85).aspx) (I had to look it up) and my guess is that the URL replacement algorithm goes into some cycle while trying to resolve a local file. Quoting the contents of the `url` statement did not help and neither did commenting the whole line out. Removing the leading `#` prevents the exception, however.

Version used was `asset-pipeline:3.0.7`

**Comment by davydotcom** [comment]
Try using version 3.0.11 , this should be resolved
