### ISSUE TITLE
sync master and 5.0.x branches

### ISSUE THREAD

**Issue by jamesfredley** [bertramdev/asset-pipeline#355]
I am not sure of the future intent for these two branches, but here are the differences.

5.0.x is [6 commits ahead of](https://github.com/bertramdev/asset-pipeline/compare/master...5.0.x), [2 commits behind](https://github.com/bertramdev/asset-pipeline/compare/5.0.x...master) master

**Comment by codeconsole** [comment]
I think we might be able to do this a little differently.  Since this is only the grails module, can't we just add the method to GrailsSpringUtils in 6.2.2 and then update the asset-pipeline plugin to use GrailsStringUtils?

**Comment by jamesfredley** [comment]
5.0.x has all the changes from master:  https://github.com/bertramdev/asset-pipeline/compare/5.0.x...master

so closing
