### ISSUE TITLE
Asset pipeline creates and overrides grailsLinkGenerator created by ControllersPlugin

### ISSUE THREAD

**Issue by codeconsole** [bertramdev/asset-pipeline#361]
`grailsLinkGenerator` is created by the [UrlMappingsPlugin](https://github.com/grails/grails-core/blob/f432a6a53f3f82066c53d7ab1cbdc27200f4d57f/grails-plugin-url-mappings/src/main/groovy/org/grails/plugins/web/mapping/UrlMappingsAutoConfiguration.java#L50-L55)

Since the asset-pipeline-grails depends on this plugin, 

https://github.com/bertramdev/asset-pipeline/blob/5a7b347295a7d6901d1772763b467404af9ba955/asset-pipeline-grails/build.gradle#L119

this code doesn't do anything useful and can be deleted:

https://github.com/bertramdev/asset-pipeline/blob/6c58b3bc09ea27907ba6d401f6fb9ec7eeefb55c/asset-pipeline-grails/src/main/groovy/asset/pipeline/AssetPipelineGrailsPlugin.groovy#L120-L122

Causes:
```
Overriding bean definition for bean 'grailsLinkGenerator' with a different definition: replacing [Root bean: class=null; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; fallback=false; factoryBeanName=org.grails.plugins.web.mapping.UrlMappingsAutoConfiguration; factoryMethodName=grailsLinkGenerator; initMethodNames=null; destroyMethodNames=[(inferred)]; defined in class path resource [org/grails/plugins/web/mapping/UrlMappingsAutoConfiguration.class]] with [Generic bean: class=asset.pipeline.grails.CachingLinkGenerator; scope=singleton; abstract=false; lazyInit=false; autowireMode=1; dependencyCheck=0; autowireCandidate=true; primary=false; fallback=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null]
```

Should probably check if bean exists before creating a new one and overriding existing behavior, but I don't understand a scenario where the bean would not exist because this plugin depends on grails-plugin-url-mappings which creates it 😕

**Comment by jdaugherty** [comment]
We should close this - it's intentional that the asset plugin creates it's own version.  It's not recreating the existing ones.  https://github.com/bertramdev/asset-pipeline/pull/364

**Comment by codeconsole** [comment]
yeah, using the same class naming got me.  We definitely needed to change it to an AutoConfiguration and it is better how it is now.
