### ISSUE TITLE
Gradle plugin not rewriting relative paths

### ISSUE THREAD

**Issue by gregopet** [bertramdev/asset-pipeline#39]
I have the following asset structure in a Grails plugin:

	images/lib/fonts/glyphicons-halflings-regular.eot
	stylesheets/lib/bootstrap/bootstrap.css (references ../fonts/glyphicons-halflings-regular.eot)
	stylesheets/lib/bootstrap.css (requires bootstrap/bootstrap.css)
	stylesheets/plugin.css (requires lib/bootstrap.css)

If I use the Grails plugin under development mode, the relative font paths are correctly overwritten to work from `plugin.css` (e.g. lib/fonts/glyphicons-halflings-regular.eot)

When using `grails package` however (I'm assuming `com.bertramlabs.plugins:asset-pipeline-gradle:2.5.0` is responsible for this) the paths do not get overwritten and the resulting CSS file references `../fonts/glyphicons-halflings-regular.eot` from `plugin.css` which the browser interprets as `http://mydomain/fonts/glyphicons-halflings-regular.eot` where it can't find them.

**Comment by davydotcom** [comment]
this may be fixed in 2.5.8

**Comment by davydotcom** [comment]
this should be fixed by now please let me know if its still an issue
