### ISSUE TITLE
Can't use assets in application from inline-plugin in non-default folders

### ISSUE THREAD

**Issue by kdickerson** [bertramdev/asset-pipeline#47]
If assets in the plugin are stored in a non-default folder (i.e., any folder but "images", "javascripts", or "stylesheets") they can't be accessed from the application that depends on the plugin.

I don't know if this is limited to "inline plugins" or not; I haven't tried packaging and installing the plugin.

Grails documentation for using inline plugins: http://grails.github.io/grails-doc/3.0.x/guide/plugins.html#creatingAndInstallingPlugins

--

To Reproduce:

    > grails create-plugin simplePlugin
    > grails create-app simpleApp
    > echo include 'simplePlugin', 'simpleApp' > settings.gradle
    > mkdir simplePlugin\grails-app\assets\other

Place an image, "image.png", into simplePlugin\grails-app\assets\images
Place an image, "image2.png", into simplePlugin\grails-app\assets\other

Edit simpleApp\build.gradle and add:

    dependencies {
      compile project(":simplePlugin")
      ....
    }

Edit simpleApp\grails-app\views\index.gsp and add:

    <p>
      Image from plugin default folder: <img src="${assetPath(src:'image.png')}" /><br />
      Image from plugin non-default folder: <img src="${assetPath(src:'image2.png')}" />
    </p>

Run the application:

    > cd simpleApp
    > grails
    grails> run-app

Load the default index page: http://localhost:8080/

image.png will load properly, image2.png will return a 404 error.

--

Grails: 3.0.9
OS: Win 7 64-bit
Java: 1.7

Dependency Report Output:

    \--- org.grails.plugins:asset-pipeline: -> 3.0.8
         +--- org.mozilla:rhino:1.7R4
         \--- com.bertramlabs.plugins:asset-pipeline-core:2.5.0
              +--- org.mozilla:rhino:1.7R4
              +--- com.google.javascript:closure-compiler:v20141023
              |    +--- com.google.javascript:closure-compiler-externs:v20141023
              |    +--- args4j:args4j:2.0.26
              |    +--- com.google.guava:guava:18.0
              |    +--- com.google.protobuf:protobuf-java:2.5.0
              |    +--- com.google.code.gson:gson:2.2.4
              |    \--- com.google.code.findbugs:jsr305:1.3.9
              \--- commons-logging:commons-logging:1.1.1 -> 1.2

--

I turned on logging for the asset-pipeline but saw nothing enlightening regarding this issue.

I would have attached the example application / plugin, but can't attach zip files.

**Comment by davydotcom** [comment]
this is actually a bug in the grails gradle plugin for plugin packaging... @graemerocher

**Comment by longwa** [comment]
As a workaround, you can augment the processResources task dependency in a plugin project's `build.gradle` to copy the lib directory:
```
task copyLibAssets(type: Copy) {
    from "${project.projectDir}/grails-app/assets/lib"
    into "${processResources.destinationDir}/META-INF/assets"
}
project.tasks.getByName('processResources')
```

**Comment by davydotcom** [comment]
https://github.com/grails/grails-core/pull/9414
