### ISSUE TITLE
Coffeescript does not produce sourcemaps

### ISSUE THREAD

**Issue by cgeo7** [bertramdev/asset-pipeline#48]
Coffeescript sourcemaps are not created, so the sources are not available in the browser developer tools

**Comment by kevana** [comment]
We got around this with babel-asset-pipeline by having Babel generate inline source maps as data-urls in the files. I don't know if asset-pipeline has any way to preserve existing maps when it runs assets through the Closure Compiler.

**Comment by davydotcom** [comment]
Seems coffee is dying so not planning on adding this support
