### ISSUE TITLE
Can't read assets from app in development mode - Project with multiple hierarchy plugins.

### ISSUE THREAD

**Issue by satshil** [bertramdev/asset-pipeline#50]
We are migrating from grails 2.4 to 3.0.8

==================
project structure
==================
Main app > plugin 1 > plugin 2 > plugin 3

where plugin 1 has dependency on plugin 2 and plugin 2 has dependency on plugin 3

assests exist in main project and plugin 3. (js, css and less)

===================================================
Build.gradle Settings (same settings added for both plugin3 and app)
==================================================
buildscript {
    ext {
        grailsVersion = project.grailsVersion
    }
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
	classpath 'com.bertramlabs.plugins:asset-pipeline-gradle:2.6.2'
        classpath 'com.bertramlabs.plugins:less-asset-pipeline:2.6.2
    }
}
....
....
apply plugin: 'asset-pipeline'
...
...
assets {
	minifyJs = false
	minifyCss = false
	excludes = ['**/less/*.less', '**/mixin/*.less','**/.svn/**','**/examples/**']
	includes = ['bootstrap.less']
	configOptions = [
		less: [
		  compiler: 'less4j' 
		]
	]
}

dependencies {
    ...
    ...
    runtime "org.grails.plugins:asset-pipeline"
    ...
    ...
}

==================================
Problem
==================================
When I run the app in development mode I can see it compiles all the assets from plugin. But it does not compile any asset from app. Which results in not recognizing assets from app at runtime. 

Observations:
Running run-app run task assetCompile only on plugin not on app.

Running package command executes task assetCompile on plugin as well as on app. Which copies assets twice inside app.jar and inside plugin.jar.

**Comment by davydotcom** [comment]
You should not be running assetCompile on a plugin. The grails gradle plugin will automatically package all assets from a plugin into `META-INF/assets`.
