### ISSUE TITLE
Grails plugin portal version out of date?

### ISSUE THREAD

**Issue by sgates** [bertramdev/asset-pipeline#51]
Why does http://repo.grails.org/grails/repo/org/grails/plugins/asset-pipeline/ show 2.6.5 / 3.0.9 as the latest versions but on the official grails plugin portal: https://grails.org/plugin/asset-pipeline the version is still 2.5.9?

Are the 2.6.x and 3.0.x versions not stable?

**Comment by davydotcom** [comment]
they are. something is wrong with `grails.org` not updating the version on the latest. I have reported to @graemerocher

**Comment by sgates** [comment]
Great, thanks!

**Comment by davydotcom** [comment]
fixed.
