### ISSUE TITLE
smarter include/exclude logic

### ISSUE THREAD

**Issue by tedder** [bertramdev/asset-pipeline#52]
Java's file globbing leaves much to be desired. For instance, it isn't possible to say "include x/** except for x/bad/**". This can be handled by letting PathMatcher take regular expressions (currently PathMatcher is hardcoded to 'glob:<string>') or by adding a third filter so the precedence given as "exclude X, except include Y, except exclude Z" (currently it's X and Y in that order).

Z could be a regex filter, which makes it completely backwards-compatible. Alternately, checking X/Y for `glob:` / `regex:` and defaulting to the former is pretty easy and not out of line with the check for a leading `**/` that is already there.

Have any thoughts on this?

**Comment by davydotcom** [comment]
this was added to 2.6.9 and up
