### ISSUE TITLE
[LESS] additional space in css selector

### ISSUE THREAD

**Issue by yuki-takei** [bertramdev/asset-pipeline#53]
[SomMeri/less4j](https://github.com/SomMeri/less4j/issues/314) v1.15.0 has a problem.

[additional space in css selector since 1.15.0 #314](https://github.com/SomMeri/less4j/issues/314)

@davydotcom 
The commit c190ebf you did looks like fix this problem, but v1.15.1 has no effect according to the comment (-> https://github.com/SomMeri/less4j/issues/314#issuecomment-149560377 ).

Could you upgrade less4j to v1.15.2 ?

**Comment by davydotcom** [comment]
will do thanks for letting me know

**Comment by yuki-takei** [comment]
@davydotcom

Thanks for your work.
However this problem is reproduced in the specific situation.

* Grails 3.0.9
* build.gradle
```
buildscript {
	dependencies {
		classpath "org.grails:grails-gradle-plugin:$grailsVersion"
		classpath 'com.bertramlabs.plugins:asset-pipeline-gradle:2.6.9'
	}
}
...
dependencies {
	runtime "org.grails.plugins:asset-pipeline"
	assets "com.bertramlabs.plugins:less-asset-pipeline:2.6.9"
}
```

It works fine when I did `gradle war` and deployed the war file to Tomcat.
However It is reproduced when I ran `gradle run`.

**Comment by davydotcom** [comment]
Run latest Grails 3 plugin 3.0.14 or 15

**Comment by yuki-takei** [comment]
This works for me. Thank you!

```
dependencies {
    runtime "org.grails.plugins:asset-pipeline:3.0.15"
    assets "com.bertramlabs.plugins:less-asset-pipeline:2.6.9"
}
```
