### ISSUE TITLE
Fonts inside Fonts folder under Plugin's Assets not processed. Both in Development and 

### ISSUE THREAD

**Issue by satshil** [bertramdev/asset-pipeline#54]
Projetcs
=========
MyApp > pluginOne > pluginTwo

I have my fonts folder inside pluginTwo. I add the above setting but no help. My system can't recognize the fonts :(
pluginTwo 
     -  grails-app
         -assets
          -fonts
            -fontawesome-webfont.eot
          -stylesheets
            -sample.css

I found following setting to be ad for for plugin but adding it inside application.groovy dosen't made any difference.

grails.assets.plugin.”plugin-name”.includes=[“fonts/*”]

This works in grails 2.4 and above as I tested 2.4.3 but broken in 3.*.*

I took help from following blogs
http://www.technologyscout.net/2015/07/adding-assets-in-grails-3/
http://davydotcom.com/blog/2015-01-29-grails-3-0-0-m1-asset-pipeline-tips-tricks

**Comment by davydotcom** [comment]
this is not a working feature in grails 3 due to the transition to binary plugins.
