### ISSUE TITLE
asset-pipeline-gradle:2.4.3 not working with io.ratpack:ratpack-gradle:1.1.1

### ISSUE THREAD

**Issue by javazquez** [bertramdev/asset-pipeline#55]
Hello, 

I am running io.ratpack:ratpack-gradle:1.1.1 and I don't seem to be able to get the plugin(asset-pipeline-gradle:2.4.3) to work. I get a 404 for application.js file.

when I use io.ratpack:ratpack-gradle:0.9.18, I don't have this issue. Is there a configuration I am missing when using 1.1.1?

build.gradle gist 
https://gist.github.com/javazquez/02e8112864ae1a5da545

ratpack.groovy gist
https://gist.github.com/javazquez/0ad0c1ab72b7270be4bd

thanks,
Juan

**Comment by davydotcom** [comment]
have you tried 2.6.4 of the gradle asset-pipeline plugin by chance. Also rat pack moved to using continuous build so you need to configure the asset path for development mode

**Comment by javazquez** [comment]
Thanks for the follow up. Please forgive my ignorance, I don't understand what "configure the asset path for development mode" means. Is there a project I can reference? Thanks for you time, I appreciate the help.

**Comment by davydotcom** [comment]
You need to point to the assets folder due to a change in the continuous build system (temporary)

https://github.com/robfletcher/midcentury-ipsum/blob/master/src/main/kotlin/com/energizedwork/midcenturyipsum/Main.kt#L55

**Comment by javazquez** [comment]
Updated to 2.6.4 and added the following

  module(AssetPipelineModule) { config ->
      // only matters at development time, and path is relative to the build path
       config.sourcePath ="../../../src/assets"             
    }    

Thank you! that did the trick.
