### ISSUE TITLE
Duplicate assets inflating grails app war

### ISSUE THREAD

**Issue by satshil** [bertramdev/asset-pipeline#58]
I am working on grails 3.0.9
Project structure
==============
app
    ..
    --assets
          -- test1.css
plugin
   ..
    --assets
         -- test2.css
         -- test3.css

On creating war
----------------------
app.war
   --assets
       -- test1.css
       -- test2.css
       -- test3.css
   --web-Inf
       -- plugin.jar
         --META-INF
           -- test2.css
           -- test3.css

**Comment by davydotcom** [comment]
have an example ? web-inf seems odd as we never place anything in that folder.

**Comment by satshil** [comment]
My mistake... corrected the project structure in main question.  Its META-INF folder inside the plugin jar

**Comment by davydotcom** [comment]
plugins bundle the original source assets in META-INF/assets . This is how the main application can utilize them and bundle them together (process them). consider META-INF/assets a "source" folder in the plugin jar
