### ISSUE TITLE
How Can I Use asset-pipeline In A SpringBoot Web Application？？？

### ISSUE THREAD

**Issue by shellyxue** [bertramdev/asset-pipeline#62]
Dear Author：
         I want use asset-pipeline in my springBoot web application ，do you have
some idea or suggestion to me? I hope get your help.thank

**Comment by falleco** [comment]
Hey! Does this help: http://davydotcom.com/blog/2014-12-21-spring-boot-with-the-asset-pipeline

**Comment by davydotcom** [comment]
The asset-pipeline-spring-boot plugin works and that guide should help you out but might be good to elaborate in the docs. Closing this issue and raising a new one about documentation
