### ISSUE TITLE
Grails 3 asset mapping being ignored from plugin

### ISSUE THREAD

**Issue by ctoestreich** [bertramdev/asset-pipeline#63]
It would appear that setting the following in a plugin's config does not get picked up from an application.  You have to directly add this to your application level config.  Other non-asset-pipeline config properties are read just fine from the plugin's `application.yml`

```
grails:
    assets:
        mapping: foo-assets
```

**Comment by ctoestreich** [comment]
def loadBefore = ['assetPipeline']

**Comment by jpsalvadorm63** [comment]
grails:
    assets:
        mapping: 'http:.....com/assests'

is it OK ?

**Comment by davydotcom** [comment]
This is because your plugin is probably loading after asset pipeline and
not before... you could change load order to loadBefore
