### ISSUE TITLE
Make spring-boot servlet filters generic

### ISSUE THREAD

**Issue by augustl** [bertramdev/asset-pipeline#67]
Hello there!

I'm currently investigating using asset-pipeline in a stand-alone app where I don't want to use the "default" servlet to serve files.

I found these two filters:

https://github.com/bertramdev/asset-pipeline/blob/rel-2.6.9/asset-pipeline-spring-boot/src/main/groovy/asset/pipeline/springboot/AssetPipelineFilter.groovy
https://github.com/bertramdev/asset-pipeline/blob/rel-2.6.9/asset-pipeline-spring-boot/src/main/groovy/asset/pipeline/springboot/AssetPipelineDevFilter.groovy

They do exactly what I want, but I'm not able to use them since I don't use spring-boot.

The dev filter can be made to work simply by removing the line in `init()` that calls into `WebApplicationContextUtils` - the return value is not used for anything.

The normal filter also uses `WebApplicationContextUtils` but it doesn't seem to use the resulting `applicationContext` for much. So it shouldn't be too much work to turn that into an abstract class or something, and put it in asset-pipeline-core, or maybe create a new asset-pipeline-servlet project.

I can contribute a pull request for this, but I thought I'd discuss it with you first, to see if this is something you'd be interested in!

**Comment by davydotcom** [comment]
You want a standalone servlet implementation?

**Comment by augustl** [comment]
Yeah, that's exactly what I need. It seems to me that it wouldn't be too difficult to make a standalone servlet implementation that is an abstract class or something like that, where you can override "getResource" and "getGzippedResource", for example.

**Comment by davydotcom** [comment]
It isn’t hard no but asset-pipeline-spring-boot is the spring boot module. You’d have to make a asset-pipeline-servlet sub project

**Comment by augustl** [comment]
That makes sense!

I'll go ahead and write a pull requests that:

1) Adds generic servlets to a new sub-project, asset-pipeline-servlet
2) Rewrite asset-pipeline-spring-boot to use the servlets in asset-pipeline-servlet

**Comment by augustl** [comment]
Closing this - created a separate pull request for it at #70
