### ISSUE TITLE
Implement file watching

### ISSUE THREAD

**Issue by augustl** [bertramdev/asset-pipeline#72]
I would like a file watching based setup that I could hook into asset-pipeline-servlet. This would also be useful for asset-pipeline-gradle. So it would make sense to implement this watcher in asset-pipeline-core. Alternatively as a separate asset-pipeline-watcher module.

In asset-pipeline-servlet, I'm imagining an implementation that works like this:

* Have the AssetPipelineDevServlet aware of some kind of watcher interface
* In `onFilter` of the servlet filter, check if the watcher is currently processing assets. If it is, block the request.
* As soon as the processing is finished, continue the request

That way, I can just reload the page and have the request block/hang while asset pipeline finishes processing in the background.

I haven't investigated the details yet, so I'm not confident on the implementation details. Looking at asset.pipeline.AssetCompiler, it seems to me that we could write a WatchingAssetCompiler that takes options similar to the AssetCompiler, and creates its own private AssetCompiler that it uses under the hood, and sets up file system watching to invoke the compiler when relevant files change. What do you think about this?

I've never implemented file system watching on the JVM, so I don't have any opinions on what library one would use to back this up. Do you have any opinions?

When these questions are answered, I can get to work on implementing it if that's OK with you!

**Comment by augustl** [comment]
Did some quick googling that I should have done before posting this issue. Seems like the file system watching part is already covered by the JVM, in https://docs.oracle.com/javase/7/docs/api/java/nio/file/WatchService.html

This would require java 1.7 or later, is that OK?

**Comment by augustl** [comment]
Added an initial draft implementation of the file watching part.

https://github.com/augustl/asset-pipeline/blob/3a858b26f96a7f831e435a37eb6ff3831d83120d/asset-pipeline-core/src/main/groovy/asset/pipeline/WatchingAssetCompiler.groovy
https://github.com/augustl/asset-pipeline/blob/3a858b26f96a7f831e435a37eb6ff3831d83120d/asset-pipeline-core/src/main/groovy/asset/pipeline/WatchingAssetCompilerRunnable.groovy

It seems to work fine - it prints in the console when files are changed.

**Comment by davydotcom** [comment]
Asset-pipeline gradle supports file watching already

**Comment by augustl** [comment]
Ah, good to know.

All I can find is `project.task('asset-watch')` which is commented out. How do you trigger the file watching?

**Comment by davydotcom** [comment]
gradle -t assetCompile

**Comment by augustl** [comment]
Ah, so it piggybacks on gradle to do that.

There's a big benefit to writing it by hand, and that's the ability to write the servlet so that it waits with serving the file until the asset compilation has completed. That is a huge win workflow wise, as you can be confident that you get the latest assets when you refresh the browser, as opposed to having to wait for the background job to finish before refreshing.

What do you think?

**Comment by davydotcom** [comment]
In grails land we dont do this we compile on the fly and do a cache diff
check... it has no need to wait either way. In production stuff is packaged
and diff check is not necessary

**Comment by augustl** [comment]
Yeah, this is definitely for development only.

What is the cache diff doing? Perhaps I could implement something like that for asset-pipeline-servlet. Is it something along the lines of checking the source file for modifications, and have the serving setup either read from cache, or compile and put into the cache if the cache is outdated?

**Comment by augustl** [comment]
Hello again :) Closing this one, I got into some details and realized I don't really know how I want my setup to be. I obviously want to use gradle for building so that Jenkins can build a finished app with assets pre-compiled. So I need to think about how I want to combine my current setup with a gradle based asset build.

**Comment by davydotcom** [comment]
Yea all built in... Look at development mode or the situation of the manifest.properties doesn't exist for spring boot it calls an endpoint that does that

**Comment by davydotcom** [comment]
And that cache file is persisted too it's called the .asscache
