### ISSUE TITLE
Ability to share LESS mixins across code bases?

### ISSUE THREAD

**Issue by danhyun** [bertramdev/asset-pipeline#75]
I'm trying to establish a shared set of LESS mixins that can be consumed by multiple subprojects in a multi project Gradle setup.

As an example, there are two Gradle subprojects, A and B.

Should LESS files from A be able to reference mixins from B?

Here's the relevant info:

`A/A.gradle`
```gradle
apply plugin: "com.bertramlabs.asset-pipeline"
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.6.9"
  }
}

assets {
  minifyJs = true
  minifyCss = true

  excludes = ['**/_*.less']

  from "$projectDir/src/less"
  from "$rootDir/B/src/assets/shared-styles"
}
```

`A/src/less/example.less`
```less
@import (reference) "../../../B/src/assets/shared-styles/_palette.less";
body {
 background-color: @purple;
}
```

`B/src/assets/shared-styles/_pallete.less`
```less
@purple: #5a2a6b;
```

`./gradlew assetCompile -s`
```bash
Caused by: java.lang.RuntimeException: File was not sourced from the same ScanDirectory D:\projects\demo\B\src\assets\shared-styles\_palette.less scanDir: D:\projects\demo\A\src\less
        at asset.pipeline.fs.FileSystemAssetResolver.relativePathToResolver(FileSystemAssetResolver.groovy:166)
        at asset.pipeline.fs.AbstractAssetResolver.resolveAsset(AbstractAssetResolver.groovy:77)

        at asset.pipeline.fs.FileSystemAssetResolver.getAsset(FileSystemAssetResolver.groovy:77)

        at asset.pipeline.fs.AssetResolver$getAsset$0.call(Unknown Source)
        at asset.pipeline.AssetHelper.fileForUri(AssetHelper.groovy:48)
        at asset.pipeline.AssetHelper$fileForUri$3.call(Unknown Source)
        at asset.pipeline.less.AssetPipelineLessSource.relativeSource(AssetPipelineLessSource.groovy:51)
```

**Comment by danhyun** [comment]
Seems like we could use [`Path#relativize`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#relativize(java.nio.file.Path)) to find the path to the resolver in [`FileSystemAssetResolver`](https://github.com/bertramdev/asset-pipeline/blob/8283ff3c9cfb76f795caf949d81b83d1c6449033/asset-pipeline-core/src/main/groovy/asset/pipeline/fs/FileSystemAssetResolver.groovy#L195)

```groovy
@CompileStatic
	protected iterateOverFileSystem(File dir, List<String> excludePatterns, List<String> includePatterns, List<AssetFile> fileList, String sourcePath) {
		dir.listFiles()?.each { File file ->
			def relativePath = relativePathToResolver(file, sourcePath)
```

**Comment by davydotcom** [comment]
You could probably haven't tried yet it was written  originally to account for something relativized didn't

**Comment by danhyun** [comment]
I had a sneaking suspicion that this should work.. and it does!

I just had to adjust my `example.less` to make the reference to `_palette.less` "local"

So instead of this:

```less
@import (reference) "../../../B/src/assets/shared-styles/_palette.less";
body {
 background-color: @purple;
}
```

It should be

```less
@import (reference) "_palette.less";
body {
 background-color: @purple;
}
```

Output css is what I was expecting.

The only thing is that IntelliJ gives me a red squiggly line but that's fine.

**Comment by davydotcom** [comment]
thats because intellij is not very intelligent

**Comment by danhyun** [comment]
The conflict is just that IntelliJ is following LESS standards (relative to
"this" file) vs what AP does which is resolve against all of the scan
directories. Maybe the Gradle AP plugin can inform IntelliJ to consider
against all scandirs?

On Mon, Feb 8, 2016 at 2:31 PM, David Estes <notifications@github.com>
wrote:

> thats because intellij is not very intelligent
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bertramdev/asset-pipeline/issues/75#issuecomment-181471574>
> .
>



-- 
Thanks,

Daniel Hyun
blog: http://hyunlabs.com/
