### ISSUE TITLE
gradle - do not compile/copy assets for every Jar task

### ISSUE THREAD

**Issue by zyro23** [bertramdev/asset-pipeline#76]
maybe there is a more sensible default which jar tasks are relevant? or some sort of configuration could make sense?

for custom jar tasks (e.g. a pathing jar, source jars, etc.), depending on `assetCompile` and having the assets copied into the jar is not very useful.

ref. https://github.com/bertramdev/asset-pipeline/blob/master/asset-pipeline-gradle/src/main/groovy/asset/pipeline/gradle/AssetPipelinePlugin.groovy#L85

**Comment by flofreud** [comment]
The generated pathingJar for windows contains the assets and therefore also an asset pipeline manifest file. Due to that one no asset reloading is happening.

As workaroung the manifest can be unset in the Bootstrap.groovy:

```
        if (Environment.isDevelopmentMode()) {
            // reloading issue cause by asset compilation on pathing jar generation for windows
            asset.pipeline.AssetPipelineConfigHolder.manifest = null
        }
```

**Comment by davydotcom** [comment]
fixed now configurable as 

```
assets {
   jarTaskName='jar'
}
```

**Comment by davydotcom** [comment]
should mention the defaults are also more sensible now you may not even need to do this

**Comment by zyro23** [comment]
thanks!!
