### ISSUE TITLE
Minifying Transpiled JavaScript

### ISSUE THREAD

**Issue by atreides322** [bertramdev/asset-pipeline#77]
I am trying to use errbuddy/babel-asset-pipeline to transpile JSX to JavaScript. I was a little surprised that it wasn't minified by asset-pipeline. Looking at `asset.pipeline.AssetCompiler`, it is correctly identifying the file as `asset.pipeline.babel.JsxAssetFile` and invoking the `asset.pipeline.babel.BabelProcessor`, but because the contentType is `'text/jsx'`, it doesn't get minified. However, `asset.pipeline.babel.JsxAssetFile#contentType` is a list and it contains `'application/javascript'`. What if there was a way to have the minify check look to see if the contentType contains `'application/javascript'`? Or a way to customize what will get minified?

**Comment by davydotcom** [comment]
the contentType in the spec for an AssetFile should always be set to only what the final or requested content type is which is not text/jsx its always compiling to js
