### ISSUE TITLE
Remove Java 7 dependency for application runtime (not for asset pre-processing)

### ISSUE THREAD

**Issue by wijnand1** [bertramdev/asset-pipeline#79]
A Grails application that uses the asset-pipeline cannot be run in a web container running on Java 6. However, the requirement for Java 7 seems to originate from processes that are performed at the stage of building a WAR file (e.g the file glob-bing in FileSystemAssetResolver. The release notes also mention the closure compiler as needing java 7; again, a pre-processing step)

When a few non-essential Java 7 constructs (e.g the usage of the diamond operator in Urls.java) are taken out, it seems to me on quick inspection that a separate jar file could be constructed that cannot be used to pre-process any assets, but that only contains the functionality needed by the Grails application running in the web container. This jar could then be compiled at the Java 6 language level, and could be included in a WAR instead of the (current) asset-pipeline-core-2.6.7.jar. 

This is important, as one generally has no control over the Java version customers are running on their web server, so Java 7 requirement can cause problems. Of course, there is no problem to conform to the Java 7 requirement at the pre-processing/WAR production stage.

**Comment by davydotcom** [comment]
not planning on doing this atm but it is possible if someone wants to rework some things. we are almost to java 9 land now though so time to at least upgrade to java 7
