### ISSUE TITLE
Production Assets With Custom Replacements

### ISSUE THREAD

**Issue by csamuels** [bertramdev/asset-pipeline#82]
We have Handlebars templates and Javascripts that rely on the LinkGenerator's createLink method to generate the link based on the environment.

We have this working in development mode by implementing a custom Processor, and doing a regex replacement for ${createLink( {{map }} ):

```
class JsLinkProcessor implements Processor {
    @Autowired
    LinkGenerator linkGenerator

    String process(String inputText, AssetFile assetFile) {
       inputText = inputText.replaceAll(regex, { all, params ->
            def list = Eval.me("[$params]")
            try {
                def link = linkGenerator.link(list)
                log.warn("Generated link $link for $all in file $assetFile.name")
                link
            } catch (Exception e) {
                log.warn("Failed to generate link for $all and $params in file $assetFile.name: $e")
                throw e;
            }
        })
```
...

In production mode, the processor doesn't seem to be invoked at all and none of the links are being replaced.

Is there a way to get the assets to run through the processor in Production mode?

Thanks for any assistance.

**Comment by csamuels** [comment]
Forgot to include the regex for reference:

   ` def regex = /\$\{\s*createLink\s*\(([^\)]*)\)\s*\}/`

**Comment by davydotcom** [comment]
you want this to happen on your build phase, meaning the processor and spec need to be on gradles build classpath or gants
