### ISSUE TITLE
Configure rubygems.org repository URL

### ISSUE THREAD

**Issue by radarsh** [bertramdev/asset-pipeline#83]
I am building my Grails 3 app in an environment that doesn't have access to rubygems.org. So, whenever I try to assemble the project, I get:

```
ERROR: Could not find a valid gem 'compass' (= 1.0.3), here is why:
        Unable to download data from https://rubygems.org/ - Connection reset by peer (https://rubygems.org/specs.4.8.gz)
```

and several other lines hinting a connectivity issue to rubygems.org.

I do have access to an internal Artifactory instance where the gems are cached. Is there a way to configure asset-pipeline to use the internal repository rather than rubygems.org?

**Comment by davydotcom** [comment]
So forgot to respond to this it seems... sass asset pipeline no longer needs jruby
