### ISSUE TITLE
Matched directive additional params

### ISSUE THREAD

**Issue by theaspect** [bertramdev/asset-pipeline#85]
We want be able to pass additional params to directive.

But here https://github.com/bertramdev/asset-pipeline/blob/4fb87700f842d27692bbe633bef8f9cf8ae74244/asset-pipeline-core/src/main/groovy/asset/pipeline/DirectiveProcessor.groovy#L175

Passed only first agrument. Was it intentional? If we pass `directive.trim()` instead of `unprocessedArgs[0]` it shouldn't affect current plugins. But inside custom plugin we can split this string and extract arguments

**Comment by davydotcom** [comment]
fixed
