### ISSUE TITLE
Grails plugin PRs

### ISSUE THREAD

**Issue by rgoldberg** [bertramdev/asset-pipeline#95]
Where should I submit PRs for AP Grails plugin? asset-pipeline, or grails-asset-pipeline? Is it different for Grails 2 or 3? What branches for the different Grails versions? If grails-asset-pipeline is defunct, is there any way to close it? Or at least add a big warning to the main page that instructs people to use asset-pipeline instead.

**Comment by davydotcom** [comment]
grails-asset-pipeline is grails 2 now master branch... the grails 3 plugin
is now part of the main asset pipeline multiproject repository. Its all mid
move

**Comment by rgoldberg** [comment]
Thanks.

I'm using Grails 2, so I submitted some PRs in grails-asset-pipeline, and I fixed a Grails-3-only bug in asset-pipeline.  I assume that you'll take care of any changes applied in grails-asset-pipeline that also should be applied to asset-pipeline, right?

**Comment by davydotcom** [comment]
those are now treated as separate library plugins ill try and do that but its no longer easy
