### ISSUE TITLE
Unexpected exclude behavior with require_tree and require_full_tree

### ISSUE THREAD

**Issue by kevana** [bertramdev/asset-pipeline#98]
It looks like asset `excludes` directives are not respected at compile or runtime when `require_tree` or `require_full_tree` is used in manifests.

Grails version: 3.1.8
asset-pipeline version: 2.8.2

 Sample app: https://github.com/kevana/grails-full-tree-exclude-example

Project structure:
```
grails-app/
    assets/
        javascripts/
            application.js
            core/
                foo.js
                foo.spec.js
```
application.js:
```
//= require_full_tree core
```

build.gradle:
```
assets {
    excludes = ["**/*.spec.js"]
}

```
application.yml:
```
grails:
    assets:
        excludes:
          - '**/*.spec.js'
```

Is there something wrong with the exclude pattern? I've tried a few different wildcard combos, haven't found one that works.
cc: @ctoestreich

**Comment by kevana** [comment]
The sample app doesn't show it but we're seeing the same behavior when the assets are contained in a plugin and the parent project tries to exclude them:

```
assets {
    configOptions = [
            plugin: [
                    'my-plugin': [
                            excludes: ["**/*.spec.js"]
                    ]
            ]
    ]
```

**Comment by davydotcom** [comment]
Excludes do not affect require directives these solely affect build time exclusion as base assets that need processed. Please see documentation at www.asset-pipeline.com

**Comment by davydotcom** [comment]
"A common configuration change for assets may be the includes/excludes patterns. These allow one to specify specific files that should not be individually required or compiled because it does not make sense for them to be individually compiled"

**Comment by kevana** [comment]
So there's no way conceptually to tell asset pipeline to include all the files under a tree in a manifest while simultaneously excluding a pattern?

**Comment by davydotcom** [comment]
Nope for this i recommend moving those files you want to exclude out of the
tree into anither location
